### ISSUE TITLE
Credential Error

### ISSUE THREAD

**Issue by ljtill** [Azure/AzOps#11]
**Describe the bug**

`WARNING: Retry Count: 1 Caught Exception for Credential Error for Get-AzResource for /subscriptions/00000000-0000-0000-0000-00000000000/resourceGroups/user-keyvault`

**Steps to reproduce**

1. Invoking the `Initialize-AzOpsRepository` cmdlet

**Comment by uday31in** [comment]
https://github.com/Azure/azure-powershell/pull/12041
https://github.com/Azure/azure-powershell/issues/9448
