### ISSUE TITLE
Add detail on expected format of AZURE_CREDENTIALS parameter

### ISSUE THREAD

**Issue by dtrac** [Azure/AzOps#134]
It's not immediately clear what format is expected for the AZURE_CREDENTIALS parameter that is passed in during docker run (e.g via an Azure DevOps Pipelines variable).

**Comment by uday31in** [comment]
Since this is repo for Action, please see Enterprise-Scale repo for info:

https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-github.md#4-connect-github-to-azure
