### ISSUE TITLE
Broken Link (Template)

### ISSUE THREAD

**Issue by telmosampaio** [Azure/AzOps#15]
**Describe the bug**
The **ARM Template** link in the README files returns a 404

**Steps to reproduce**

1. Click on the link ;)

**Screenshots**

**Comment by krnese** [comment]
@telmosampaio  - can you pls point to the link?

**Comment by azMantas** [comment]
I do believe that we are talking about the same link. 

> For quick start, an ARM template that can be deployed at the tenant
