### ISSUE TITLE
AzOps-Pull workflow fails: The property 'Id' cannot be found

### ISSUE THREAD

**Issue by rwaal** [Azure/AzOps#162]
My goal is to implement Enterprise-Scale "in-a-box". I have followed the steps exactly as described here: https://github.com/Azure/Enterprise-Scale/tree/main/docs/enterprise-scale-iab

Things go wrong at point 11 in [Setup GitHub CI/CD pipeline](https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/setup-git-cicd.md). The workflow **AzOps-Pull** fails, reporting the following error:

```
Write-AzOpsLog: /var/lib/app/entrypoint.ps1:88
Line |
  88 |              Write-AzOpsLog -Level Error -Topic "entrypoint" -Message  …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [00:40:38.7498] (entrypoint) The property 'Id' cannot be found
     | on this object. Verify that the property exists.
```
I verified that I executed the steps in [Deploy your tenant](https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md) correctly. The SPN was created and assigned permissions several hours before. 

**Steps to reproduce**

1. Follow the steps in [Deploy your tenant](https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md).
2. Follow the steps in [Setup GitHub CI/CD pipeline](https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/setup-git-cicd.md), and at point 11, run the **AzOps-Pull** workflow. 

**Screenshots**

![image](https://user-images.githubusercontent.com/28002263/94893494-9b727e00-0487-11eb-9905-f2887e2fd0b4.png)

**Comment by uday31in** [comment]
Unfortunately it is known issue and we are actively working with engineering team to fix this as per https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Known-Issues.md#management-group-api-failures

please re-run  workflow (you many have to try several times).

**Comment by rwaal** [comment]
Indeed @uday31in, after running the workflow four times it finally completed successfully. Thanks for your response.
