### ISSUE TITLE
Policy enforcement property not captured in Policy Assignment

### ISSUE THREAD

**Issue by AndyHerb** [Azure/AzOps#171]
Having run AzOps-Pull the output doesn't appear to capture whether a Policy Assignment's enforcement property has been disabled/enabled.  This can essentially lead to the incorrect assumption that the Policies in place are active, when in reality they are not

**Comment by AndyHerb** [comment]
Is there any update on this?

**Comment by krnese** [comment]
Are you referring to the output after making a policy assignment?

**Comment by AndyHerb** [comment]
I’m referring to the fact that a Policy can be Assigned but not Enforced (i.e it's disabled), which isn't overly useful for a Governance change tracking solution, as you would be completely unaware via AzOps that your policy wasn't doing anything (if it were a Deny or DeployIfNotExists)

**Comment by krnese** [comment]
Correct, and that will be visible within the properties. This is subject to how one would author definitions and expose requisite parameters to reflect the policy effect.
