### ISSUE TITLE
Need to use/impliment Azure AzOps

### ISSUE THREAD

**Issue by sabil05** [Azure/AzOps#174]
Hello Team, 

Myself Mohammed Sabil currently working with Fujitsu as Technical Consultant. I am interested in your project and wanted to use/implement Azure AzOps and showcase it. 

It would be really appreciate if you can help me understand the Azure AzOps project so that I can utilized it for use case and see how it is beneficial for our project. 

Awaiting for your response. 

Thank you in advance!
Sabil.

**Comment by sabil05** [comment]
Hello Team, 

May I know do you have any update?

Thanks.

**Comment by uday31in** [comment]
What kind of help can we provide?

I recommend to start here

https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md
https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Deploy-reference-implentations.md
https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/getting-started.md

**Comment by sabil05** [comment]
@uday31in Thank you for your response. 

Enterprise-Scale is also know as AzOps? As I am trying to deploy a 3 tier application architecture using AzOps. Just wanted to know.

Thank you.

**Comment by sabil05** [comment]
Just now try to deploy the Enterprise-Scale (wingtip) foundation by using the above given url. I am getting an authorization error. Does it require any specific privilege's to do the deployment. 

The client 'Mohammed.Sabil' with object id '15b302b8-db0e-467a-9f49-046742753ca3' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20201124170300' or the scope is invalid. If access was recently granted, please refresh your credentials.

**Comment by uday31in** [comment]
https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-at-root-scope--to-deploy-enterprise-scale-reference-implementation
