### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by stuartphillipsfujitsu** [Azure/AzOps#181]
Not sure if this is a bug or not but I am seeing a number of false positives when generating a PR using an Azure DevOps pipeline when it comes to resource tags. The order in which tags are outputted in .AzState changes between runs, so false positive changes are detected. As an example, in my latest run, hundreds of files are reported as changed when in fact the tag names and values are exactly the same, they are just in a different order in the ‘Tags’ section.

**Steps to reproduce**

1. Add tags to a resource, run the pipeline
2. Run the pipeline again (without making any changes to any resource)

**Screenshots**
![image](https://user-images.githubusercontent.com/62669981/100789257-1c111480-340e-11eb-9a0b-01d4a2bee6a0.png)

Thanks!

**Comment by uday31in** [comment]
@daltondhcp - can you please tell us which resource is it?

**Comment by stuartphillipsfujitsu** [comment]
Hi, I have the issue on NSG's, Firewall Policy and vnet's. I have not tested anything else at the moment.

**Comment by daltondhcp** [comment]
Thanks for reporting @stuartphillipsfujitsu, I have been able to reproduce the issue and we will make sure to release a fix for this a.s.a.p.
