### ISSUE TITLE
Use classes for handling $global:SCMPlatform specific code segments

### ISSUE THREAD

**Issue by JanneMattila** [Azure/AzOps#185]
While going through the codebase I see following pattern repeating quite frequently:

```powershell
switch ($global:SCMPlatform) {
  "GitHub" {
    # Do something
  }
  "AzureDevOps" {
    # Do something
  }
}
```

Would it make sense to use classes for encapsulating this kind of code?

I'll give example:

```powershell
class Repository {
  [string] $HeadRef # Set parameters once

  [void] Checkout([string ]$branch) {
    Write-Host "Checking out $branch"
  }
}

class GitHubRepository : Repository {
  [void] CreatePullRequest() {
    Write-Host "Creating Pull Request using GitHub API"
  }
}

class AzureDevOpsRepository : Repository {
  [void] CreatePullRequest() {
    Write-Host "Creating Pull Request using Azure DevOps API"
  }
}

# Usage example with GitHub
$repository = [GitHubRepository]::new()
$repository.Checkout("main")    # Prints: Checking out main
$repository.CreatePullRequest() # Prints: Creating Pull Request using GitHub API

# Usage example with Azure DevOps
$repository = [AzureDevOpsRepository]::new()
$repository.Checkout("main")    # Prints: Checking out main
$repository.CreatePullRequest() # Prints: Creating Pull Request using Azure DevOps API
```

In above example there is "base provider class" for repository. 
It contains all the code that are shared across both GitHub and Azure DevOps (and all potential future repositories).

Quite much of the codebase has this current structure due to parameter differences, which we could now handle in single place. Example `$HeadRef` which we would now set in the start based on those provider specific parameter names (`$global:AzDevOpsHeadRef`, `$global:GitHubHeadRef`).

All areas that do then differ would be handled in the repository specific implementation.
In above example that would be `CreatePullRequest` since it relies calling service specific APIs.

Thoughts about this approach?

**Comment by FriedrichWeinmann** [comment]
Well, with the major refactor just in (see psf branch) it's no longer quite as prevalent as it used to.
An interesting approach for sure, however, would reduce command complexity.
Since we no longer use global variables, you'd need to specify those through parameters on the constructor instead, but that's more of a technicality, doesn't change the concept.

**Comment by JanneMattila** [comment]
Hey thanks for the hint! I'll take closer look at the `psf` branch. Do you know timeline when it's going to be merged to `main`?

**Comment by FriedrichWeinmann** [comment]
Sorry for the late reply.
Got delayed by a slight dose of overwork :(
I'm back on it, will need more testing and tuning with the team, so I can't give you a definitive timeline yet other than "soon".

**Comment by ljtill** [comment]
@JanneMattila thank you for opening this issue, as @FriedrichWeinmann mentioned we're actively working on a major new release of [AzOps](https://github.com/azure/azops/tree/dev) - See the _dev_ branch.

With the new version we've decided to move away from embedding the SCM controls within the module to a platform agnostic approach where-by we invoke native `Git` commands from within the CI/CD workflow (GitHub Actions / Azure Pipelines). Please visit the [AzOps-Accelerator](https://github.com/azure/azops-accelerator) repository for more information and examples.

If you have any further questions, please don't hesitate to reach out.
