### ISSUE TITLE
Using PowerShell Gallery for sharing AzOps module

### ISSUE THREAD

**Issue by JanneMattila** [Azure/AzOps#186]
AzOps PowerShell module is currently buried inside this codebase. It makes it slightly more challenging to use it in local development when you want to repeat and repeat the deployment workflows.

Now you need to pull source to local disk and import it from there:

```powershell
# First time you clone
Set-Location C:\GitHub\Azure\
git clone https://github.com/Azure/AzOps.git

# Take updates
Set-Location C:\GitHub\Azure\AzOps\
git pull
Import-Module C:\GitHub\Azure\AzOps\src\AzOps.psd1 -Force

# Use Invoke-AzOps* commandlets
```

Alternative method would be that it would be available in [PowerShell gallery](https://www.powershellgallery.com/). 

Then process would be like any other PowerShell module usage:

```powershell
Install-Module AzOps
# and
Update-Module AzOps

# Use Invoke-AzOps* commandlets
```

I know this is not super critical but might open further scenarios and
speed up development since you could use this in your custom processes.

**Comment by FriedrichWeinmann** [comment]
With the new refactor (see "PSF" branch) CI/CD and release to the PSGallery are definitely coming :)
Also a lot more flexibility in how you want to provision your configuration settings as well as logging

**Comment by JanneMattila** [comment]
Great! If that's already planned, then we can close this.
