### ISSUE TITLE
Discovery enhancements 

### ISSUE THREAD

**Issue by uday31in** [Azure/AzOps#2]
Support Discovery in environment with duplicate display name for management group and subscription

**Comment by daltondhcp** [comment]
- Support Partial Discovery with SPN not having full access at root (with override)
- Allow Duplicate names for MG and Subscription (with override in azops.yml)
- Discovery Deny list of Subscription/MG path for discovery (in Enterprise-Scale) in .gitignore style (.azopsignore???)
