### ISSUE TITLE
PSFTeppCompletionResult - Unrecognized Command

### ISSUE THREAD

**Issue by wavegh** [Azure/AzOps#249]
**Describe the bug**

**Steps to reproduce**

1. GitHub> Create Template from AzOps-Accelerator
2. GitHub> Settings > Add secrets
3. GitHub>Actions>AzOps - Pull results in 'New-PSFTeppCompletionResult' unrecognized command

**Screenshots**
![image](https://user-images.githubusercontent.com/80415303/112779335-1fa75780-900c-11eb-8196-1d85de960bef.png)

**Comment by ljtill** [comment]
@FriedrichWeinmann notified me today that there's a new release of [PSFramework](https://www.powershellgallery.com/packages/PSFramework) which includes a fix for this issue. 

I'm planning to test and update the module dependencies either by the end of this week or early next.

**Comment by ljtill** [comment]
The required version of `PSFramework` has now been incremented which includes a fix for this issue.
