### ISSUE TITLE
Existing PR from automated - Better handling

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#284]
**Describe the solution you'd like**
I'm not sure if the pipeline failing because of an existing PR is optional.

If this occurs then there's a finite number of options available to the customer, suggest we link to an FAQ page in the error message if there's already an existing PR.

<img width="784" alt="Screenshot_1" src="https://user-images.githubusercontent.com/17914476/114052879-55f39b00-9886-11eb-827c-b4ab0e611516.png">

**Comment by Gordonby** [comment]
I'm going to lean on a new task, as its actually quite valid that someone might not want to autocomplete the PULL PR's, but deal with them manually.  Expect a future PR, for a different ADO pipeline sample :)

```
- task: Bash@3
        displayName: "Check for existing Pull Request"
        name: prexist
        inputs:
          targetType: "inline"
          script: |
            echo "Checking for existing, active Pull requests between $(workingbranch) and $(targetbranch)"
            ACTIVEPRS=$(az repos pr list \
              -s "$(workingbranch)" \
              -t "$(targetbranch)" \
              --status active \
              --query "[].[pullRequestId, title, createdBy.displayName]")
            
            echo "Active Pull requests"
            echo $ACTIVEPRS

            PRCOUNT=$(echo $ACTIVEPRS | jq -r length)
            echo "$PRCOUNT pull request found"
            
            if [ "$PRCOUNT" -eq "0" ]
            then
              echo "Setting Job variable to Create PR"
              echo "##vso[task.setvariable variable=createpr]true"
            else
              echo "Setting Job variable to Skip PR Creation as it already exists"
              echo "##vso[task.setvariable variable=createpr]skip"
            fi
            
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
```

then leveraging a condition in the PR task
`condition: and(contains(variables['state'], 'continue'),contains(variables['createpr'], 'true'))`

**Comment by daltondhcp** [comment]
Publish guidance on how this should be approached.

**Comment by daltondhcp** [comment]
Guidance will be published in the FAQ.
