### ISSUE TITLE
When importing PSFConfig, enable exceptions

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#289]
**Describe the bug**
Often when making changes to the settings.json, you can inadvertently cause issues, which get reported as Warnings by the Import-PSFConfig.  In my experience, all of these warnings are worth stopping the pipeline for instead of letting it run to the end where it won't work properly.

Import-PSFConfig -Path $settingsPath -Schema MetaJson **-EnableException**

**Comment by ljtill** [comment]
Thanks for opening this issue @Gordonby.

Agreed - We will get this implemented on the Accelerator repository; we have a dependency (#280) on resolving all warning messages before we can implement this, but I'll keep this thread open until this is update is merged.
