### ISSUE TITLE
Push job fails in Pull run - You need the Git 'GenericContribute' permission

### ISSUE THREAD

**Issue by rohancragg** [Azure/AzOps#299]
**Error**

```
Generating script.
Script contents:
git push origin automated -f
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/42fac68b-b57f-4cdc-8dbf-a49a37a3cb5b.sh
remote: 001f# service=git-receive-pack
remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\<GUID>', scope 'repository'.
remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\<GUID>', scope 'repository'.
fatal: unable to access 'https://dev.azure.com/[ORG]/[PROJECT]/_git/[REPO]/': The requested URL returned error: 403
```

**Steps to reproduce**

Configured AzOps-Accellerator and pipelines as described here: https://github.com/azure/azops-accelerator/wiki/azure-pipelines#configure-permissions

Build Service account has:

- Contribute
- Contribute to pull requests
- Create branch
- Create tag
- Force push (rewrite history, delete branches and tags)
- Read

Manually ran AzOps - Pull job

**Comment by rohancragg** [comment]
I tried something which has now resolved this for me.

I had previously added these permissions (and a few more as mentioned above) to 

`Project Collection Build Service Accounts` (of which `[Project] Build Service ([ORG])` is a Member and therefore inherits permissions).

Now I have also added these permissions to `Project Collection Build Service ([ORG])`

- Contribute
- Contribute to Pull requests
- Create branch

This has now resolved the git push error.

So, this is slightly different to what is advised in https://github.com/azure/azops-accelerator/wiki/azure-pipelines#configure-permissions which currently says 

> Select the `[Project] Build Service ([Organization])` account, and configure the permissions above.

**Comment by rohancragg** [comment]
A similar answer here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/5159#issuecomment-519660646

**Comment by rohancragg** [comment]
Re-opening because I believe that the docs need amended: https://github.com/azure/azops-accelerator/wiki/azure-pipelines#configure-permissions

**Comment by ljtill** [comment]
Thanks for reporting this issue @rohancragg - We'll review the docs and get them updated.

**Comment by daltondhcp** [comment]
Closing as the latest wiki refresh for ADO as per https://github.com/azure/azops/wiki/azure-pipelines cover this.
