### ISSUE TITLE
Property 'Id' cannot be found

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AzOps#3]
As per: https://docs.microsoft.com/en-us/powershell/module/az.accounts/Connect-AzAccount?view=azps-4.2.0

The below:
https://github.com/Azure/AzOps/blob/99c1e0cf2b17be976368b8ba6a0e9ada938c964f/entrypoint.ps1#L28

Should Be: 

Connect-AzAccount -Tenant $credentials.tenantId -ServicePrincipal -Credential $credential -SubscriptionId $credentials.subscriptionId -WarningAction SilentlyContinue | Out-Null

as it gives errors: 

![image](https://user-images.githubusercontent.com/1243172/84656794-29dbe780-af0b-11ea-9682-69cb9977284e.png)

**Comment by ljtill** [comment]
Thanks for submitting this @liamfoneill, investigating this issue and will update shortly.

**Comment by matt-FFFFFF** [comment]
I get this too, from the warning I'd say the issue was here:

https://github.com/Azure/AzOps/blob/99c1e0cf2b17be976368b8ba6a0e9ada938c964f/src/public/Initialize-AzOpsRepository.ps1#L122

![image](https://user-images.githubusercontent.com/16320656/84658154-5b55b280-af0d-11ea-9445-46f6219cfdb9.png)

**Comment by uday31in** [comment]
@liamfoneill @matt-FFFFFF  - how long ago did you create SPN and granted permission at tenant scope?

**Comment by matt-FFFFFF** [comment]
A couple of hours @uday31in

**Comment by mjazwiecki** [comment]
just received the same error:
![image](https://user-images.githubusercontent.com/51361414/91531648-69608000-e90d-11ea-97ab-c23aead44d4e.png)
any idea how to make it work?
thanks
