### ISSUE TITLE
Code generation not escaping parameters in Policy definitions when raw template is output

### ISSUE THREAD

**Issue by GLink** [Azure/AzOps#302]
**Describe the bug**
When using the "Core.ExportRawTemplate": true setting in the AzOps-Accelerator to produce raw ARM templates the resulting code for policies needs to escape the parameter in the policy with [ to avoid it being parsed as a parameter from the ARM template.

Generated code now:
          "then": {
            "effect": "[parameters('effect')]"
          }

Needs to be:
          "then": {
            "effect": "[[parameters('effect')]"
          }

**Steps to reproduce**

1. Specify "Core.ExportRawTemplate": true in the settings.json of the AzOps-Accelerator
2. Make a change in the policy definition
3. Run the Push as part of the PR

**Screenshots**
![image](https://user-images.githubusercontent.com/2191774/114833608-11a95300-9dd0-11eb-9e78-7b5274b9d592.png)

**Comment by uday31in** [comment]
ExportRawTemplate flag is no longer required and will be removed in future release as we are defaulting to ARM template by default.
