### ISSUE TITLE
Discovery with "Tenant Root Goup" only is failing

### ISSUE THREAD

**Issue by hjscherer** [Azure/AzOps#32]
My tenant has only the "Tenant Root Group" and two subscriptions assigned to it. No child managmement goups have been created.

1. Start discovery using the GH action.
2. Following discovery error occurs: 
```
Write-AzOpsLog: /action/entrypoint.ps1:93
Line |
  93 |              Write-AzOpsLog -Level Error -Topic "git" -Message $PSItem …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [2020-06-22 14:26:32.3805] (git) [2020-06-22 14:26:32.3721]
     | (pwsh) Cannot find any Management Groups. Does the Service
     | Principal/User have the appropriate privileges on the root
     | Management Group or is the Management Group hierarchy not yet
     | created?
```

Workaround:
Creating a single management group under Tenant Rout Group solves this issue.

**Comment by ljtill** [comment]
This looks like an issue with the label creation (system), I'll dig into the REST call and update this thread shortly.

**Comment by hjscherer** [comment]
Updated comment this was the wrong error message in the original description
