### ISSUE TITLE
Allow managed identity based service connection in DevOps to run AzOps

### ISSUE THREAD

**Issue by gbordier** [Azure/AzOps#325]
Requesting high privileged service principal with a simple secret can be challenging at large customers. It would be much easier to allow a managed identity to run the AzOps scripts. 
Managed Identity based service connection look like they can be a good candidate for this.

**Comment by ljtill** [comment]
Thanks for opening the issue @gbordier.

Within either of the implementations ([GitHub Actions](https://github.com/Azure/AzOps-Accelerator/tree/main/.github/workflows) / [Azure Pipelines](https://github.com/Azure/AzOps-Accelerator/tree/main/.pipelines)) the `Connect-AzAccount` blocks in both Push & Pull models can be customised based upon the requirements of the deployment. Our default implementation uses Service Principals, but this could be replaced with Managed Identity (-Identity) if required and using Self Hosted runners.

**Comment by ljtill** [comment]
I'm going to close this issue, please feel free to re-open if you have any further questions.
