### ISSUE TITLE
AzOps.Core.State not being picked up from Condition in DynamicTree

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#337]
**Describe the bug**
After switching to use the DynamicTree settings file format, the State directory is not being picked up properly.
The pipeline logs show;
![image](https://user-images.githubusercontent.com/17914476/117802452-64e6b800-b24d-11eb-91a7-b9611ab3db0f.png)

Whilst the settings file is set;
![image](https://user-images.githubusercontent.com/17914476/117802542-834cb380-b24d-11eb-9f3f-5179d02b031c.png)
https://dev.azure.com/mscet/_git/CAE-AzOps-MultiEnv?path=%2Fazops-canary-settings.json

**Steps to reproduce**

1. Refer to https://dev.azure.com/mscet/_git/CAE-AzOps-MultiEnv?path=%2Fazops-canary-settings.json
2. Run Pull pipeline

**Screenshots**
![image](https://user-images.githubusercontent.com/17914476/117801429-2f8d9a80-b24c-11eb-9f1e-85a7b3a74c12.png)

**Comment by jshield** [comment]
The issue appears to be that the underlying filter in the PSF is broken, looking for illegal environment variables

i.e. ENV:\System.CollectionId rather than SYSTEM_COLLECTIONID.
