### ISSUE TITLE
PR to Main gets nuked if AzOps - Push fails and AzOps - Pull runs after

### ISSUE THREAD

**Issue by FallenHoot** [Azure/AzOps#342]
**Issue**
When you do a PR to Main it works as it should, but if the AzOps - Push fails and AzOps - Pull does its recheck on the state of Azure, it nukes the PR. 

![image](https://user-images.githubusercontent.com/19664186/118325319-9a1c3000-b503-11eb-9bcc-76d3d1989c90.png)

It is not a big issue, but you simply have to edit or push the feature_release back to main to see if the AzOps - Push works this time. Could cause issues.

**Comment by daltondhcp** [comment]
Added condition to the workflow in https://github.com/Azure/AzOps-Accelerator/pull/91 so the subsequent pull only runs if the push was successful.
