### ISSUE TITLE
ARM Template: esux.json used in the wiki no longer exists

### ISSUE THREAD

**Issue by ShantnuS** [Azure/AzOps#350]
**Describe the bug**
The esux.json ARM template is used in the Introduction of the Wiki, in the Goal state section: https://raw.githubusercontent.com/Azure/AzOps/main/template/esux.json

It should be located here: https://raw.githubusercontent.com/Azure/AzOps/main/template/esux.json
(i.e. in the "template" folder which no longer exists). 

**Steps to reproduce**

1. Open the following page: https://github.com/azure/azops/wiki/introduction#goal-state
2. Click on the quick start ARM Template link: 
![image](https://user-images.githubusercontent.com/17111246/119689481-cb202d00-be40-11eb-8751-cce7001f1516.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17111246/119689393-b80d5d00-be40-11eb-8d13-5e099790b6d4.png)

**Comment by daltondhcp** [comment]
Thank you for reporting, while we fix this, please refer to https://github.com/Azure/Enterprise-Scale#deploying-enterprise-scale-architecture-in-your-own-environment for up to date reference implementation links.
