### ISSUE TITLE
Pull workflow failed - Unable to Install-Module -Name AzOps -Force

### ISSUE THREAD

**Issue by faister** [Azure/AzOps#362]
**Describe the bug**
Run Install-Module -Name AzOps -Force
Install-Package: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and
     | module name 'AzOps'. Try Get-PSRepository to see all available
     | registered module repositories.

Error: Process completed with exit code 1.

**Steps to reproduce**

1. Manually invoked Pull workflow. 
2. Pull workflow failed at the "Dependencies" stage, with the above error message.

**Screenshots**

**Comment by FriedrichWeinmann** [comment]
Hello Fai,
thank you for reporting this and apologies for the inconvenience.
There was a temporary service outage of the PowerShell Gallery service we download our packages from (An expired certificate).
Your entire workflow should thus have failed without doing any additional harm.

The issue has been resolved and the workflows should again work as usual.

**Comment by faister** [comment]
Perfect! Thank you Friedrich.
