### ISSUE TITLE
Add generator metadata for generated templates

### ISSUE THREAD

**Issue by BernieWhite** [Azure/AzOps#363]
**Describe the solution you'd like**

Templates generated with AzOps don't follow [best practises](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/best-practices). However this is understandable given the context and how they are intended to be used.

It would be helpful though to add generator metadata so that these generated templates can be identified and excluded with CI processes that lint and enforce best practises. aka. [PSRule for Azure](https://github.com/microsoft/PSRule.Rules.Azure).

For example Bicep and PSArm currently implement a generator metadata block.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "_generator": {
      "name": "bicep",
      "version": "0.3.539.46024",
      "templateHash": "871445258948351894"
    }
  },
  "resources": []
}
```

Something similar for AzOps would be helpful.

**Comment by BernieWhite** [comment]
@ljtill  Thinking this through further. It may not be required to include AzOps version/ templateHash just _name_ to reduce any potential template churn. What do you think?

**Comment by ljtill** [comment]
@BernieWhite We are planning to implement this construct into the generated templates.
We've got a couple other work items which we are wrapping up and then we will get this added.
