### ISSUE TITLE
Bug Report - User data displayed in output

### ISSUE THREAD

**Issue by extmaper** [Azure/AzOps#365]
**Describe the bug**
https://github.com/Azure/AzOps/blob/main/src/functions/Initialize-AzOpsRepository.ps1#L76 displays user information in action output. This exposes regulatory related data and could also potentially create confusion for consumers of AzOps.

**Steps to reproduce**

1. Run AzOps pull action
2. Check output log from action under initialize phase to find displayed user

**Screenshots**

**Comment by daltondhcp** [comment]
Closed by #366
