### ISSUE TITLE
Validate fails due to empty or missing /tmp/OUTPUT.md

### ISSUE THREAD

**Issue by segraef** [Azure/AzOps#374]
**Describe the bug**

Once a PR raised `validate.yml` runs but exists with the following error (see screenshot).
[Invoke-AzOpsChange.ps1](https://www.powershellgallery.com/packages/AzOps/1.2.0/Content/internal%5Cfunctions%5CInvoke-AzOpsChange.ps1) and [New-AzOpsDeployment.ps1](https://www.powershellgallery.com/packages/AzOps/1.2.0/Content/internal%5Cfunctions%5CNew-AzOpsDeployment.ps1) create an empty /tmp/OUTPUT.md or no OUTPUT.md at all if the state is left untouched during a PR.

**Steps to reproduce**

1. Create a PR without any change on the state, just on the `README.md` e.g..
2. AzOps - Validate runs but fails.

**Screenshots**

![image](https://user-images.githubusercontent.com/19261257/123504856-508c3c80-d68e-11eb-92f4-53496e55c86a.png)

**Comment by JustinGrote** [comment]
Workaround:
```

      - name: "Results"
        shell: pwsh
        run: |
          if (-not (Test-Path $tmp/OUTPUT.md)) {
            "### No Operational Changes were detected"
          } else {
            gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/OUTPUT.md
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by JustinGrote** [comment]
Also doesn't work if a bicep template is in use.

![image](https://user-images.githubusercontent.com/15258962/125126901-a1e5f400-e0b0-11eb-8aa0-20f5d4d95cf8.png)

**Comment by daltondhcp** [comment]
> Also doesn't work if a bicep template is in use.
> 
> ![image](https://user-images.githubusercontent.com/15258962/125126901-a1e5f400-e0b0-11eb-8aa0-20f5d4d95cf8.png)

Tested this with bicep earlier today and it seems to be working fine for me. (https://github.com/daltondhcp/azops-test2/pull/66) 
Did you test this after our latest release? 

Related to changes outside of azops scope such as .md etc, we will probably add a path trigger condition to only run validate on .json and .bicep charges.

**Comment by daltondhcp** [comment]
Solved with for the validate workflow as per https://github.com/Azure/AzOps-Accelerator/pull/91.
