### ISSUE TITLE
No subscriptions in MG structure leads to AzOps Pull failure

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#377]
**Describe the bug**
I have two top level MG's.  Canary and Prod.
Canary has no subscriptions.
When AzOps runs, i get a warning
```
WARNING: [12:29:06][Get-AzOpsSubscription] No relevant subscriptions found!
```
However it then just fails with
```
Initialize-AzOpsRepository: /home/vsts/work/_temp/bd38a29c-b729-41a6-8271-e03523d4f0eb.ps1:3
Line |
   3 |  Initialize-AzOpsRepository -Rebuild
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The 'Initialize-AzOpsRepository' command was found in the
     | module 'AzOps', but the module could not be loaded. For more
     | information, run 'Import-Module AzOps'.
``

**Steps to reproduce**

1. Bootstrap a MG structure with no subscriptions
2. Try to AzOps pull it.

**Screenshots**
![image](https://user-images.githubusercontent.com/17914476/123968788-788ddf80-d9af-11eb-857e-d58851e10758.png)

**Comment by daltondhcp** [comment]
Thank you for reporting! This is related to that Get-AzResourceProvider currently requires subscription access. We are looking to move away from the Az PowerShell cmdlets across the board and instead do generic REST calls which will solve this particular issue.
![image](https://user-images.githubusercontent.com/16622613/124282201-dc004480-db4a-11eb-8161-a3a754dc6269.png)

Until we have changed this, access to at least one subscription will be required for a successful pull. Note that this subscription does not need to reside in the management group hierarchy that you are pulling.

**Comment by Gordonby** [comment]
Granted this is more of an issue in test environments.. 🧷 

As you've advised, I've worked around it by giving it access to a subscription in another MG. Thanks @daltondhcp 🚀 

```Powershell
$sp = Get-AzADServicePrincipal -DisplayName AzOpsCanary
New-AzRoleAssignment -ObjectId $SP.Id -RoleDefinitionName Reader -Scope "/subscriptions/$((Get-AzContext).Subscription.Id)"
```
