### ISSUE TITLE
PartialMgDiscoveryRoot being ignored 

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#378]
The SPN being used by AzOps has got Tenant root permissions, "/".

The settings.json has been set such
```
"Core.PartialMgDiscoveryRoot": ["prod"],
```

However a subscription that is directly on the tenant root is causing the AzOps pull to fail.

There's 2 problems I can see here.
1. Discovery is not actually scoped to the provided Mg root
2. A subscription not having a Mg causing AzOps to fail. (The subscription, incidentally was used as part of the Connect-AzAccount command when we logged in)

**Screenshots**
![image](https://user-images.githubusercontent.com/17914476/124130461-b7d33380-da76-11eb-9795-5ebe840b4906.png)

**Comment by daltondhcp** [comment]
After thorough testing with an SPN that has '/' permissions, partial discovery enabled and subscription directly under the root management group, I have unfortunately not been able to reproduce this issue. 
Feel free to re-open issue if you are encountering this again.
