### ISSUE TITLE
Management Group not found

### ISSUE THREAD

**Issue by JulianHayward** [Azure/AzOps#380]
**Describe the bug**
'AzOps - Pull' - Initialize - fails after new ManagementGroup is deployed  

Whilst 'AzOps - Push' completes successful AND the Management Group is visible in the Portal, the 'AzOps - Pull' fails at 'Initialize' step with 'Management Group not found'

I guess this a timing issue? the issue only occurred once btw.

**Steps to reproduce**

1. create new Management Group

**Screenshots**

![image](https://user-images.githubusercontent.com/45695032/125038142-5a05a380-e095-11eb-9928-d87d0d3cf315.png)

**Comment by daltondhcp** [comment]
This is indeed a timing issue related to replication in ARM and depends on deployment region and which region the subsequent GET call ends up. We will investigate what we can do to handle this more gracefully without a rerun.

**Comment by daltondhcp** [comment]
Closing this as it is related to ARM replication and we won't invest time to work around this in AzOps at this time.
