### ISSUE TITLE
Why is Invoke-AzOpsChange not an exported function?

### ISSUE THREAD

**Issue by JustinGrote** [Azure/AzOps#384]
```
          $module = Get-Module -Name AzOps
          $module.Invoke({ Invoke-AzOpsChange -ChangeSet $diff -WhatIf })
```

Why do this instead of just export the function and use Invoke-AzOpsChange directly?

**Comment by ljtill** [comment]
@JustinGrote - We're in the process of refactoring this - a recent merge into the main branch includes this change where will be replacing these cmdlets which will both be exported, aiming to have this release out next week.

`Initialize-AzOpsRepository` -> `Invoke-AzOpsPull`
`Invoke-AzOpsChange`  -> `Invoke-AzOpsPush`
