### ISSUE TITLE
Need step by step documentation on how to run AzOps using Azure Pipelines

### ISSUE THREAD

**Issue by sssangle** [Azure/AzOps#392]
Hi Team,

I followed the AzOps wiki (https://github.com/azure/azops/wiki/azure-pipelines ) where most of the content is about the configurations of pipelines .

Can you please guide or add step by step document on how to use and run the pipelines ?

Which pipeline needs to run first and and how to observe changes and do modifications so that it will help to try this AzOps

**Comment by Gordonby** [comment]
Couple of links that might help @sssangle .

I have (scripted)[https://github.com/Gordonby/Snippets/blob/master/EntScale/Prepare-ADO-Project.sh] that entire setup using the az devops cli. It creates a new project, does almost all the config, and uses the [Multi Environment](https://github.com/Azure/AzOps-Accelerator/tree/main/.pipelines/samples#multi-environment) sample, and it leverages the **new Verify workflow** that's super cool. 🚀 

![image](https://user-images.githubusercontent.com/17914476/125695320-f75b8a3c-058b-4f9d-b5a1-73aaee9c8e3c.png)

**Comment by sssangle** [comment]
@Gordonby : The configuration part is mostly clear with the wiki document (https://github.com/azure/azops/wiki/azure-pipelines ) but after that need step which pipeline should triggered first to get the current Azure state and which pipeline to run for modifications. In configurations and wiki document only 2 pipelines are mentioned (Pull and Push) and nothing mentioned about validate pipeline . I am looking for steps on how to start after configuration complete
