### ISSUE TITLE
Moving subscriptions

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/AzOps#399]
**Describe the bug**
Currently i try to move a subscription from the staging aria to its new location. After changing the code noting happens.

**Steps to reproduce**

- Remove the "resources" from microsoft.management_managementgroups-XXX.json and copy them to the new microsoft.management_managementgroups-YYY.json didn't work
- Remove the "resources" from microsoft.management_managementgroups-XXX.json and copy them to the new microsoft.management_managementgroups-YYY.json and copy the subscription directory over to the new location this also didn't work

What am i doing wrong here?

**Comment by daltondhcp** [comment]
Hi Eelco,

You can move a subscription to a new management group by adding the subscription to the resources block in the the **target** microsoft.management_managementgroups-{id}.json or by [deploying a new template](https://docs.microsoft.com/en-us/azure/governance/management-groups/manage#move-subscriptions-in-arm-template) that makes the move. 
After following the regular deployment workflow (Pull Request (Validate) -> Merge (Push) -> Successful deploy (Pull), the subscription move should be reflected both in the platform and in the git repository. No need to manually move any folders. 

See my example below where I am moving the connectivity subscription under the enableDemo-connectivity mg to the ctx01-connectivity mg. 
![image](https://user-images.githubusercontent.com/16622613/126463316-967cbd28-0a4c-4120-8f2e-d51286630a7c.png)
![image](https://user-images.githubusercontent.com/16622613/126464532-18d731b4-5c22-48c6-809c-338bd582e65f.png)

**Comment by EelcoLabordus** [comment]
Hallo Johan,

I tried to do what you describe but it still didn't work:

![change](https://user-images.githubusercontent.com/75468927/126475286-c54f5199-8490-4722-bf6e-34804061ac48.png)

Result in push pipeline:

![change](https://user-images.githubusercontent.com/75468927/126475485-b4a0074d-625c-4b7c-8e21-ce51b06912b2.png)

Any advice?

Eelco

**Comment by daltondhcp** [comment]
Sorry for not pointing that out in my previous comment; the name property needs to be changed to also reflect the new parent management group `{managementGroupId/{subscriptionId)/}`. So in your case you need to change it from `HIP/` to `ELA/`

**Comment by EelcoLabordus** [comment]
Hallo Johan,

That solve the problem, it is now working. 

This was the only combination i didn't try.

Thanks,

Eelco
