### ISSUE TITLE
AzOps Pipeline - Connect to Azure update

### ISSUE THREAD

**Issue by NicholasFry-6989** [Azure/AzOps#400]
**Describe the solution you'd like**
When running an AzOps pipeline, the Connect to Azure tasks selects the first available subscription, even if it is in a 'Warned' state.

It would be useful to define the default subscription selected for the pipelines to connect to.
![connectToAzure-WarnedState](https://user-images.githubusercontent.com/59557053/126465428-82e7bc25-b311-4696-962e-f8491f8599c7.jpg)

**Comment by daltondhcp** [comment]
To ensure that this is handled in a deterministic manner, our standard pipelines actually already use the ARM_SUBSCRIPTION_ID pipeline variable as input to the -SubscriptionId parameter. https://github.com/Azure/AzOps-Accelerator/blob/main/.pipelines/pull.yml#L181

Based on the name of your connect task, it looks like you are using one of our multi-environment community sample pipelines which doesn't have this incorporated. If you want it to be deterministic, simply add the -SubscriptionId parameter to the line with Connect-AzAccount in the template you are using for the [connect task](https://github.com/Azure/AzOps-Accelerator/blob/main/.pipelines/samples/Multiple-Environment/templates/AzureLoginWithSp.yml#L8)

**Comment by Gordonby** [comment]
I actually removed the explicit subscriptionId from that Connect task in this [commit](https://github.com/Azure/AzOps-Accelerator/commit/99320632743072c714104a9c273830d1bd63e747#diff-4f1ce5e8d4311d2ad71576869942df895e638ae86437dd34dfcabf9e2c13f47d)

Aside from the fact there's a warning in the logs, I don't think it's detrimental to the AzOps process. 
It can however as @daltondhcp points out be added back in, as per the starter pipeline templates.
