### ISSUE TITLE
Validate Step Fails on Resource Group Template Deployments

### ISSUE THREAD

**Issue by edm-ms** [Azure/AzOps#410]
When trying to use AzOps to deploy an ARM template in a resource group the validate step will fail on what-if because it cannot find the resource group.

What if: Switching targeted subscription in the context to '000000-f416-000-9183-2b6bf2fc5317'
[12:40:45][New-AzOpsDeployment] Attempting [Resource Group] deployment for /subscriptions/000000-f416-000-9183-2b6bf2fc5317/resourceGroups/rg-prd-eus-firewall/providers/Microsoft.Network/firewallPolicies/ruleCollectionGroups/[format('{0}/{1}', variables('fwPolicy'), parameters('ruleCollectionName'))]
Getting the latest status of all resources...

                                             
WARNING: [12:40:45][New-AzOpsDeployment] Error returned from WhatIf API: 
ResourceGroupNotFound - Resource group 'rg-prd-eus-firewall' could not be found.
What if: Performing the operation "New-AzOpsDeployment" on target "Start ResourceGroup Deployment?".
[12:40:45][New-AzOpsDeployment] Skipping deployment due to WhatIf
ResourceGroupNotFound - Resource group 'rg-prd-eus-firewall' could not be found.

--------------------------------------------------------------------------------------------------

1. Create ARM template to deploy a resource
2. Create new branch in repo
2. Place ARM template in resource group "folder" in GIT repo under "root"
3. Issue PR to trigger AzOps run

**Comment by daltondhcp** [comment]
Thank you for reporting @edm-ms - we just merged a PR that will fixes the issue. A new release will hopefully be cut tomorrow.
