### ISSUE TITLE
Adding comment in Auto State when "things" are removed from Azure.

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/AzOps#416]
When the Auto State pull request is created it will automatically create comments on part of the what-if statement.

When a policy assignement is removed by using the portal, AzOps will detect that the file (Assignment) doesn't exist anymore but there is no comment created in the Pull request that something has been removed. So now you need to validate the "Files" to see what has been changed.

Would it be possible to create a different comment when "things" are removed from Azure and not processed in the Repo. This way we can validate if the changes are valid or not.

**Comment by daltondhcp** [comment]
Will be covered in #395.
