### ISSUE TITLE
Comment cannot be longer than 150000 characters

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/AzOps#417]
**Describe the bug**
When applying multiple changes with the help of AzOps you might run into a bug that the comments cannot be larger than 15000 characters.

**Steps to reproduce**

1. Full deployment of Enterprise Scale Policies  json

**Screenshots**
![comments](https://user-images.githubusercontent.com/75468927/131090787-b6a0b943-cbbb-4a1b-b6bb-586a552a0503.png)

**Comment by SimonWahlin** [comment]
This is partly mitigated by #482
The failure should be solved by #470 

Do we still want to improve the what-if results comment feature or can this issue be closed?

**Comment by daltondhcp** [comment]
Given that #470 solves the failure, we will close this one for now and track potential future enhancements in separate issues.
