### ISSUE TITLE
Pwsh on mac - Azure AD commandlets not working

### ISSUE THREAD

**Issue by wayneme75** [Azure/AzOps#421]
**Describe the bug**
In prerequisites section there are issues running this piece of code. I am running pwsh in a terminal on a mac 
Powershell version: 7.1.4

$servicePrincipal = Get-AzureADServicePrincipal -Filter "DisplayName eq 'AzOps'"

$directoryRole = Get-AzureADDirectoryRole -Filter "DisplayName eq 'Directory Readers'"

    Add-AzureADDirectoryRoleMember -ObjectId $directoryRole.ObjectId -RefObjectId $servicePrincipal.ObjectId

**Steps to reproduce**

1. Manually created the roles and assignments in the Portal.
2. Replace Get-AzureADServicePrincipal with Get-AzADServicePrincipal (still have problems however with Get-AzureADDirectoryRole)

**Screenshots**

**Comment by daltondhcp** [comment]
Except for in [Cloud Shell](https://azure.microsoft.com/en-us/features/cloud-shell/), the AzureAD PowerShell module is [generally not supported](https://github.com/PowerShell/PowerShell/issues/11812.) in PowerShell code. 
As a workaround, may I suggest that you try running the commands Cloud Shell, or look at the example in this [issue](https://github.com/Azure/AzOps/issues/382). We will update our instructions with a platform agnostic example in the coming weeks.

**Comment by daltondhcp** [comment]
Will be solved in #382.
