### ISSUE TITLE
AzOps for Azure landing zones generates ARM templates for certain resources with "apiVerison" = "0000-00-00" during Pull

### ISSUE THREAD

**Issue by kahawai-sre** [Azure/AzOps#422]
**Describe the bug**
When AzOps runs an initial enumeration of resources, and merge into the repo, certain resources - including vWAN, Azure Firewall in Secure vHub, and Azure Firewall Policy - are imported with the correct schema, but with the "apiVersion" generated/stored as "0000-00-00" as per the example below.
Subsequent scheduled AzOps pulls skip merge and the result is that these particular templates are removed from the repo (they disappear).
Not sure if this is specific to vWAN resources/Azure Firewall Manager integration with Secure hub.

**Steps to reproduce**
1. Use Azure Landing Zones portal experience to deploy an Azure vWan with Azure Firewall (secure virtual hub)
2. Select the option to integrate (bootstrap) github with AzOps
3. After the initial "Enterprise-Scale Deployment" pull.yml action completes, under the under *Intermediate MG/Platform MG/Connectivity MG/Connectivity Subscription/ xxx-vnethub-australiaeast* Resource Group path, all templates generates (vWan, Azure Firewall .json files) appear with apiVersion = 0000-00-00
4. Subsequent scheduled pull.yml action instances run. This results in the template files that have 0000-00-00 as the apiVerison in the path above being removed (not sure why or at what step). The merge step is skipped in the action details/logs in this case (unlike the initial pull post deployment).
5. So after that the only .json template file under the *Intermediate MG/Platform MG/Connectivity MG/Connectivity Subscription/ xxx-vnethub-australiaeast* Resource Group path in the code repo is the .json for the Resource Group resource. Templates for vWan, vHub, Azure firewall are gone.

**Screenshots**
Example ARM template 
{	 
"$schema": https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#,
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [
    {
        "type": "Microsoft.Network/virtualWans",
        "name": "eslz-vwan-australiaeast",
        "apiVersion": "0000-00-00",
        "location": "australiaeast",
        "tags": null,
        "properties": {
        "disableVpnEncryption": false,
        "allowBranchToBranchTraffic": true,
        "office365LocalBreakoutCategory": "None",
        "type": "Standard",
        "virtualHubs": [
            {
            "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/eslz-vnethub-australiaeast/providers/Microsoft.Network/virtualHubs/eslz-hub-australiaeast"
            }
        ]
        }
    }
    ],
    "outputs": {}
}
![image](https://user-images.githubusercontent.com/77031653/132611194-6b64b067-ba31-4518-82d9-5ceb815a9b84.png)

**Comment by kahawai-sre** [comment]
Thanks for taking this on @daltondhcp 

I may have progressed this myself to some extent as follows. Can you please sanity check my updates below?
---
Testing the code so far it seems that Invoke-AzOpsPull as called in the github pull.yml action uses the output of "_Get-AzResourceProvider_" as the source for determining the current API version for each resource being processed.

For each resource being enumerated and "pulled" back into the AzOps state, Invoke-AzOpsPull will determine the resource type, e.g. _Microsoft.Networks/azureFirewalls_, and then do a lookup on the API version for that resource type against the Get-AzResourceProvider output.

In the case above, Invoke-AzOpsPull has authenticated using a Service Principal in the Connect task as shown below:
![image](https://user-images.githubusercontent.com/77031653/132923120-d7183b62-48e9-44e3-b80d-119059c47fda.png)

However, in this case, the subscription selected by default, "eslz-management" does not have the Microsoft.Network resource provider registered.

At this point the code cannot determine the latest apiVersion for the resource being processed, and defaults to an apiVersion of 0000-00-0 derived from AzOps resource template defaults.

Questions at this point:

- Is the summary above accurate, or is there an intent that all of the required resource providers will already be registered on subs in scope fo AzOps in some way?
- I see that when pushing _new_ resources, there is code in "NewAzOpsStateDeployment.ps1" that registers new resource providers for the target description if required (?) calling "_Register-AzOpsResourceProvider.ps1_". If the summary above is correct, could the "pull" process be improved to verify and register missing providers at the point where the code currently defaults to 0000-00-0?

**Comment by kahawai-sre** [comment]
Potentially an enhancement could be added as follows to resolve this, subject to testing:
- _Initialize-AzOpsEnvironment.ps1_, line 81: $script:AzOpsResourceProvider = Get-AzResourceProvider **-ListAvailable**
- _AzOps.psm1_, line 2913: $script:AzOpsResourceProvider = Get-AzResourceProvider **-ListAvailable**

**Comment by daltondhcp** [comment]
Awesome work and thank you for sharing your findings. 👏 
Your suggested fix looks accurate, will make sure to push fix in the coming days.
