### ISSUE TITLE
Resource discovery fails on Microsoft.VSOnline/plans

### ISSUE THREAD

**Issue by spiroskip** [Azure/AzOps#427]
**Describe the bug**
The when the pull workflow is running with settings set to "Core.SkipResource": false, an error is raised...

[14:18:20][ConvertTo-AzOpsState] Exporting AzOpsState to /home/runner/work/acme/acme/root/acme (acme)/acme-platform (acme-platform)/microsoft partner network (***)/acme-azops/./microsoft.managedidentity_userassignedidentities-acme-azops-umi.json
[14:18:20][Invoke-AzOpsScriptBlock] Tried unsuccessfully 3 out of 6 times, keeping up the fight! | GetResourceFailed : Plan not found
CorrelationId: dfefc64f-cd4e-4365-8cd4-5d4cc833d838
[14:18:30][Invoke-AzOpsScriptBlock] Tried unsuccessfully 4 out of 6 times, keeping up the fight! | GetResourceFailed : Plan not found
CorrelationId: a7a19ba8-cc7d-4105-8480-1bda48546f56
[14:18:47][Invoke-AzOpsScriptBlock] Tried unsuccessfully 5 out of 6 times, keeping up the fight! | GetResourceFailed : Plan not found
CorrelationId: 5bf4f295-cd0c-4e0d-bc35-3adb575b1f40
WARNING: [14:19:19][Invoke-AzOpsScriptBlock] Tried unsuccessfully 6 out of 6 times, giving up. | GetResourceFailed : Plan not found
CorrelationId: 3c67f5d3-650e-4fba-b74a-d662bf3fcf57
Exception: /home/runner/.local/share/powershell/Modules/AzOps/1.4.0/AzOps.psm1:1533
Line |
1533 |  …             $resourceGroups | Foreach-Object -ThrottleLimit (Get-PSFC …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The running command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop:
     | GetResourceFailed : Plan not found CorrelationId:
     | 3c67f5d3-650e-4fba-b74a-d662bf3fcf57

[14:19:20][Stop-PSFRunspace] Stopping runspace: psframework.logging
[14:19:21][Stop-PSFRunspace] Stopping runspace: psframework.taskengine
[14:19:21][Stop-PSFRunspace] Stopping runspace: psframework.logging
Error: Process completed with exit code 1.

**Steps to reproduce**

1. Run pull workflow

**Screenshots**
![image](https://user-images.githubusercontent.com/70738773/133236398-da51aa34-0028-4512-961f-2f6705b39196.png)
![image](https://user-images.githubusercontent.com/70738773/133236265-2ca5c12f-176d-41d0-b47a-8ff97d0e57d5.png)

**Comment by uday31in** [comment]
It appears that this is transient error. does it repro consistently? Is it always the same resource?

**Comment by daltondhcp** [comment]
Thank you for reporting. 
Do you happen to have an Azure DevOps subscription linked to the subscription? Looks like it is failing on some resourceGroup named `vso-rg-*******`  when trying to get the resource  `/Microsoft.VSOnline/plans/vso-plan-southeastasia`.

Unfortunately this is currently not supported - we will look at implementing a fix to exclude these resource types.

**Comment by spiroskip** [comment]
> It appears that this is transient error. does it repro consistently? Is it always the same resource?

It happens on different resources it can be reproduced

**Comment by spiroskip** [comment]
> Thank you for reporting.
> Do you happen to have an Azure DevOps subscription linked to the subscription? Looks like it is failing on some resourceGroup named `vso-rg-*******` when trying to get the resource `/Microsoft.VSOnline/plans/vso-plan-********`.
> 
> Unfortunately this is currently not supported - we will look at implementing a fix to exclude these resource types.

Yes I do have this resource. It would be good if you could have an exclusion list. Thanks

**Comment by spiroskip** [comment]
> > Thank you for reporting.
> > Do you happen to have an Azure DevOps subscription linked to the subscription? Looks like it is failing on some resourceGroup named `vso-rg-*******` when trying to get the resource `/Microsoft.VSOnline/plans/vso-plan-********`.
> > Unfortunately this is currently not supported - we will look at implementing a fix to exclude these resource types.
> 
> Yes I do have this resource. It would be good if you could have an exclusion list. Thanks

I tried it against subscription without vso-rg-*******  and it works fine. Thank you.
