### ISSUE TITLE
create Policy definition, PolicySet and Policy assignment in one go

### ISSUE THREAD

**Issue by JulianHayward** [Azure/AzOps#430]
Example:
create new Policy definition, create PolicySet leveraging the newly created Policy definition and create a Policy assignment for the newly created PolicySet - all in one go.

Finding: AzOps Push tries to create the Policy assignment at first which fails due to the Policy definition respectively the PolicySet is not created, yet.

**Comment by krnese** [comment]
Can you elaborate a bit more on the intent? AzOps is a generic pipeline for ARM templates, and policyDefinitions, policySetDefinitions, and policyAssignments are all their own explicit APIs and resources. Technically there's nothing that prevents you from achieving the above today, as you could include these resourceTypes in a single template and use dependsOn to determine the dependency graph and execution of these resources. Have you tried that?

**Comment by JulianHayward** [comment]
single template covering multiple resources the way to go - thx
