### ISSUE TITLE
Invoke-AzOpsChange -ChangeSet $Diff triggers an error when updating Local Gateway LocalNetworkAddressSpace

### ISSUE THREAD

**Issue by Freakling** [Azure/AzOps#434]
**Describe the bug**
When updating a ip address prefix list i a localNetworkGateway where there are already deployed ip address ranges, we encounter an error.

`ParentContainsErrorRecordException: /home/vsts/work/_temp/d0f02a2c-d32b-41e4-b6c9-c4872033f56a.ps1:6 
Line 6
| $module.Invoke({ Invoke-AzOpsChange -ChangeSet $diff }) 
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
| Exception calling "Invoke" with "1" argument(s): "Unable to 
| cast object of type 'Newtonsoft.Json.Linq.JValue' to type 
| 'System.String'." 
`

When we remove all the ip address ranges (empty array) the deployment succeeds, and then we can in another PR/commit re-add the correct list. However this introduces a downtime.

**Steps to reproduce**

1. Configure a Local network gateway with a set of address ranges (in parameter file)
2. Reconfigure the ip address ranges.

**Screenshots**
Logs:
![screenshot - logs](https://user-images.githubusercontent.com/6906567/135267714-46739ec3-f29d-4f33-be8d-403061d0ff5d.gif)

Network parameters file (ip address list masked, color code shows added and removed files between commits):
![screenshot - parameters](https://user-images.githubusercontent.com/6906567/135267713-5f755771-f350-4595-ad1d-7340069a00c4.gif)

**Comment by daltondhcp** [comment]
Hey @Freakling,

Thank you for reporting this.
Is this an autogenerated (from pull) or custom template you are deploying?

Thanks!

**Comment by Freakling** [comment]
AFAIK this is generated from the adventureworks enterprise-scale.
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md

**Comment by daltondhcp** [comment]
Hey @Freakling, this is now fixed and a patch release is published to PowerShell Gallery. https://github.com/Azure/AzOps/releases/tag/1.5.1
