### ISSUE TITLE
OIDC support for Github Actions

### ISSUE THREAD

**Issue by uday31in** [Azure/AzOps#462]
**Describe the solution you'd like**

https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect/

**Comment by daltondhcp** [comment]
Adding this for reference: 
https://github.com/marketplace/actions/azure-login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-powershell-windows

**Comment by daltondhcp** [comment]
I have now tested this and it works well. Will however wait until it is supported in the non-preview version of Azure CLI before updating the main workflows.
