### ISSUE TITLE
Question: What is your story on factorization and plaform versus workload?

### ISSUE THREAD

**Issue by cveld** [Azure/AzOps#463]
What is the best way to ask questions about the end game of AzOps and roadmap?

Is AzOps capable of doing factorization? E.g. a cloud competence center with various areas of concerns which ideally are spread across many git repos:
- networking
- security
- app services
- logic apps
- api management
- app gateway
- internet gateway
- service bus
- etc.

Additionally, what is your story for the workload side of things? E.g.:
- the platform side sets up the App Service Environment resources, whereas the deployment of app services are scattered across the many use case teams within the organization.
- platform provides subnets, whereas the use case teams deploy virtual machines against it
- platform provides integration service environments, the use case teams deploy logic apps against it
- etc.

**Comment by daltondhcp** [comment]
Closing as it was adressed during the community call.
