### ISSUE TITLE
Core.SkipResource: false leads to Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by bilal-ahmed-pexon** [Azure/AzOps#464]
**Describe the bug**
Hello, 

I am getting the following error when running the Pull GitHub Workflow with the parameter
`"Core.SkipResource": false`

In the "initialize section"
```
`[08:31:02][Invoke-AzOpsScriptBlock] Tried unsuccessfully 5 out of 6 times, keeping up the fight! | Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
WARNING: [08:31:35][Invoke-AzOpsScriptBlock] Tried unsuccessfully 6 out of 6 times, giving up. | Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Exception: /home/runner/.local/share/powershell/Modules/AzOps/1.6.1/AzOps.psm1:1608
Line |
1608 |  …             $resourceGroups | Foreach-Object -ThrottleLimit (Get-PSFC …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The running command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop:
     | Unexpected character encountered while parsing value: <. Path
     | '', line 0, position 0.`

```
The pipeline works fine when using `"Core.SkipResource": true`.

**Steps to reproduce**

1. Use AzOps Accelerater as Template: https://github.com/Azure/AzOps-Accelerator
2. Set `"Core.SkipResource": false`
3. Run Pull Workflow in GitHub Action

**Comment by daltondhcp** [comment]
Hello @bilal-ahmed-pexon - do you have an update on this?

**Comment by bilal-ahmed-pexon** [comment]
@daltondhcp 
Yes indeed there was a Azure DevOps Resource in that Subscription. 
However, the subscription contains the bulk of our resources thus I cannot confirm that this was exactly the culprit since it could have been one of the other resources.

Unfortunately there seems to be no option in AzOps to blacklist certain Resource Groups and the Azure DevOps Resource cannot be moved to a different subscription in the Azure portal. This lead me to use the PartialMgDiscoveryRoot option in order to skip the whole Subscription which worked but is not ideal.

I noticed the new Commit https://github.com/Azure/AzOps-Accelerator/pull/94. This looks like it would fix the issue. Is that already in the latest version?

Kind regards

**Comment by daltondhcp** [comment]
Ok, thank you for that. We just cut a new patch release for the new setting to work in AzOps, so should work in a couple of minutes.

**Comment by daltondhcp** [comment]
Please let us know when you have tested so we can close the issue. Thank you in advance!

**Comment by bilal-ahmed-pexon** [comment]
Hi,

I tried it again using the            
```
 "Core.SkipResourceType": [
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "Microsoft.VSOnline/plans"
            ],
``` 
option and making sure in the Logfiles that AzOps version `1.6.2` is being used. 
Unfortunately I still get the same error message as described in my first post.

Kind regards

**Comment by daltondhcp** [comment]
Got it. Would you mind sending me an email with the troublesome subscriptionId to jodahlbo@microsoft.com?

**Comment by bilal-ahmed-pexon** [comment]
> Got it. Would you mind sending me an email with the troublesome subscriptionId to [jodahlbo@microsoft.com](mailto:jodahlbo@microsoft.com)?

Sent! Thanks!

**Comment by bilal-ahmed-pexon** [comment]
Hi @daltondhcp ,
the pipeline started working today. However, I did not perform any changes.
I am currently using the following config:
`            "Core.SkipResourceType": [
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "Microsoft.VSOnline/plans",
                "microsoft.visualstudio/account",
                "microsoft.alertsmanagement/smartDetectorAlertRules"
            ],`

Kind regards

**Comment by daltondhcp** [comment]
Thank you for reporting this. Let me know if something changes.
