### ISSUE TITLE
Whatif exclusions

### ISSUE THREAD

**Issue by jasonbrisbin** [Azure/AzOps#475]
Describe the solution you'd like
What
I would like to be able to configure which Whatif ouputs are save using Invoke-AzOpsPush using the native filters i.e. Create, Delete, Deploy, Ignore, Modify, NoChange, Unsupported.

Why
I have a workflow which runs the following where $diff represents the current change set
```
Invoke-AzOpsPush -ChangeSet $diff -whatIf
```

The output of this command is saved to a markdown file which I then push back up to the original PR to show the changes.  Today this includes many resources that have no change at all.  Ideally I would like to be able to exclude "NoChange" and "Ignore" from this output.  Perhaps this is something that could stored as a PSF configuration option.

Context
This would be utilized in an Azure DevOps pipeline deployment.
Stage 1, Run WhatIf, capture output, and post back to original PR

**Comment by daltondhcp** [comment]
Hey Jason,

In https://github.com/Azure/AzOps/pull/470, we are introducing improvements to make the whatif output less verbose by leveraging the "human readable" string output instead of the raw json whatif output. Will this address at least part of your ask? 

Thanks,
Johan

**Comment by jasonbrisbin** [comment]
I believe the human readable format will still include resources which have No Changes or are Ignored for the deployment.  Those are the resources in particular I would like to be able to filter out.

**Comment by daltondhcp** [comment]
Absolutely, however, a lot less noise. Please give it a try once we release that. Let's keep this issue to track further improvements as the capabilities of the whatif api evolves.

**Comment by jasonbrisbin** [comment]
I took a cursory glance and it seems to me that the function Set-AzOpsWhatIfOutput is what handles the output formatting. 
 However typically this function is being passed a "results" object from Get-AzSubscriptionDeploymentWhatIfResult like this

```powershell
$results = Get-AzSubscriptionDeploymentWhatIfResult @parameters -ErrorAction Continue -ErrorVariable resultsError
....
Set-AzOpsWhatIfOutput -Results $results
```

if we added something like the following

```powershell
## AzOps.Core.WhatifExcludedChangeTypes would be a new setting in the config and would be an array
$ExcludedChangeTypes= (Get-PSFConfigValue -FullName 'AzOps.Core.WhatifExcludedChangeTypes')
if($ExcludedChangeTypes){
     $parameters.ExcludeChangeType = $ExcludedChangeTypes
}
$results = Get-AzSubscriptionDeploymentWhatIfResult @parameters -ErrorAction Continue -ErrorVariable resultsError
....
Set-AzOpsWhatIfOutput -Results $results
```

Here is the documentation on the command and available parameters
https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azresourcegroupdeploymentwhatifresult?view=azps-6.6.0
