### ISSUE TITLE
Warning about upcoming changes in  'Get-AzADServicePrincipal','Get-AzRoleAssignment','Get-AzAdUser'

### ISSUE THREAD

**Issue by daltondhcp** [Azure/AzOps#477]
Can we safely ignore/suppress these errors or do we have any dependencies on the strongly typed objects in the classes?

**Comment by daltondhcp** [comment]
![image](https://user-images.githubusercontent.com/16622613/142411497-7712d726-31d4-47a8-a5e8-186b3e3bfeaf.png)

**Comment by igorjnzl** [comment]
Hi. I believe in my environment this is causing the actions to fail. Do we have a workaround for this?

**Comment by daltondhcp** [comment]
Hey @igorjnzl - it shouldn't, can  you share some more details?
