### ISSUE TITLE
Commits with a bicep file and ARM template parameter file generates 2 deployments

### ISSUE THREAD

**Issue by StefanIvemo** [Azure/AzOps#504]
**Describe the bug**
If I commit a bicep file and a matching ARM template parameter file two deployments will be created by the push pipeline. One deployment for the bicep file and one for the parameter file.

**Steps to reproduce**

1. Create a bicep template, `storage.bicep`
2. Create an ARM template parameter file for the bicep template, `storage.parameters.json`
3. Open a Pull request. (This will generate a PR comment with the WhatIf result duplicated since two deployments are triggered)
4. Approve PR and merge to main branch
5. Two deployments will be created:
   - `AzOps-storage`
   - `AzOps-storage.parameters`

**Screenshots**
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/17688234/146940536-c2f91ffd-11d8-4e79-91c9-5831e6f5181e.png">

Screenshot shows deployment history for a commit with a bicep template named `test1.bicep` and a parameter file named `test1.parameters.json`.

**Comment by daltondhcp** [comment]
Great find! Right now, your parameters file (even for bicep deployments) will need to end with the extension `.parameters.json` similar to the examples in at https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files.

**Comment by StefanIvemo** [comment]
> Great find! Right now, your parameters file (even for bicep deployments) will need to end with the extension `.parameters.json` similar to the examples in at https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files.

Of course, I made a typo in the issue. 😊
