### ISSUE TITLE
Decommission Core.AllInOneTemplate setting

### ISSUE THREAD

**Issue by SimonWahlin** [Azure/AzOps#515]
**Describe the bug**
Setting `Core.AllInOneTemplate` to `true` in settings.json makes the initialize step in Pull pipeline error out with the following error message:  
`Add-Member: Cannot bind argument to parameter 'InputObject' because it is null.`

Setting Core.AllInOneTemplate to true will enter the if statement in the end of Get-AzOpsResourceDefinition
https://github.com/Azure/AzOps/blob/e5908199f4107cf3ee57b03b56d8e2ae3564458d/src/internal/functions/Get-AzOpsResourceDefinition.ps1#L472

The error is then thrown from Add-Member here:
https://github.com/Azure/AzOps/blob/e5908199f4107cf3ee57b03b56d8e2ae3564458d/src/internal/functions/Get-AzOpsResourceDefinition.ps1#L486

I'm not entirely sure in which scenarios we expect to have an input parameter, I'm guessing it is only for parameter files using the "generic" template. We might get away by just adding a null-check like this :

```powershell
if($parametersJson.parameters.input.value) {
    # Add property bag to parameters json
    $parametersJson.parameters.input.value | Add-Member -Name 'properties' -MemberType NoteProperty -Value $propertyBag -force
}
```

But I would rather see that we don't enter the if-statement at all if we don't need to. 

**Steps to reproduce**

1. Set Core.AllInOneTemplate to true
2. Run pull pipeline in Azure DevOps (most likely works the same in GitHub)
3. Pipeline fails with an error

**Steps to reproduce in isolation**
The following code will produce the same error
```powershell
$jsonObject = @{
    existing = 'Value'
} | ConvertTo-Json | ConvertFrom-Json

$jsonObject.doestNotExist | Add-Member -Name 'properties' -MemberType NoteProperty -Value 'somevalue' -force
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5576847/147851122-7d49f462-eb8c-4485-81c6-758f09a6eb75.png)

**Comment by daltondhcp** [comment]
Thanks for raising this. The `AllInOneTemplate` setting is a legacy setting that made its way over from the initial version of AzOps, but was never properly validated after the refactor. The plan is to remove it entirely in the future (we already started removing it from the ADO/GHA specific docs). I will use this issue to track the removal of the setting.

**Comment by SimonWahlin** [comment]
Makes sense!
Thanks for the update.
