### ISSUE TITLE
policyAssignment with invalid ResourceType.IdentityType

### ISSUE THREAD

**Issue by jsandquist** [Azure/AzOps#529]
**Describe the bug**
This behaviour surfaced in my AzOps implementation, but I am not sure I should report it here - it probably has more to do with an underlying resource provider or az powershell or something else I assume. Please just close it in that case! Anyway, here we go...
 
Since Jan 5 I see policyAssignments being picked up by the pull pipeline and committed in a state that doesn't play well with the next validate/push invocation but instead report that the deployment template file cannot be parsed.

**Steps to reproduce**

1. Modify an arbitrary policyAssignment file (containing an identity) that was pulled from Azure after Jan 5
2. Create a PR
3. Wait for the Validate pipeline/action to do its job

I did some simple tests and see the same properties with az powershell but not with az cli, e.g. something like:
```
> Get-AzPolicyAssignment -Name VNET-to-corp | Select-Object -Property * | ConvertTo-Json
> az policy assignment show --name VNet-to-corp
```

**Screenshots**

This is from my good old "eslz-in-a-box" showing that the change was picked up on Jan 5:

![image](https://user-images.githubusercontent.com/1163202/149408709-d06f58c2-e2df-46cb-a0f1-131a078562fb.png)

The diff as follows:
![image](https://user-images.githubusercontent.com/1163202/149410447-053c7c93-e4da-4d59-a6fe-00d4d8a23f29.png)

Made a minor change to the file and committed it - the Validate pipeline then report an error about invalid deployment template file, reason being the IdentityType as far as I understand.

![actions-validate-deployment-temaplte-parse-failed](https://user-images.githubusercontent.com/1163202/149407988-3ae1e99b-2cb2-46db-9fdf-df62bde8f235.jpg)

**Comment by jsandquist** [comment]
Az.Resources 5.2 maybe?

> Changed the type of member 'Identity' in PsPolicyAssignment object from PSObject to PSPolicyIdentity
-- https://github.com/Azure/azure-powershell/pull/16433

But I have no idea what I'm talking about here...

**Comment by daltondhcp** [comment]
Thank you for reporting this - I have been able to repro the issue myself and can confirm that it is related to the Az.Resource 5.2 property and the fairly [recently introduced support for UserAssignedIdentities ](https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-policy-introduces-user-assigned-msi-support-faster-dine/ba-p/2661073) in PolicyAssignments.
