### ISSUE TITLE
Invoke-AzOpsPull fails with timeout using workload federation

### ISSUE THREAD

**Issue by extmaper** [Azure/AzOps#541]
**Describe the bug**
When running workflow with Workload Federated Identity the initialize phase in Pull workflow fails with error (see screenshots). The previous phase where login happens works fine, which confirms that the WFI configuration is correct. 

**Steps to reproduce**

1. Configure Federated credentials on app registration
2. Configure workflows to use Workload Identity Federation
3. Run Pull workflow

**Screenshots**

![image](https://user-images.githubusercontent.com/56257151/150314164-48bc82a6-f1f1-4987-8c95-cf4c51c32520.png)
![image](https://user-images.githubusercontent.com/56257151/150314282-58c33bbf-19b7-4d39-bd98-ae70471151c2.png)

**Comment by daltondhcp** [comment]
Should be fixed as per update in upstream. To be verified.

**Comment by extmaper** [comment]
@daltondhcp - After running AzOps with OIDC during a couple of days I can verify that it works fine now, at least for run times in 45-50 minutes.

**Comment by daltondhcp** [comment]
Thank you! Will close the issue for now.
