### ISSUE TITLE
Guidance for AzOps usage in Azure US Government

### ISSUE THREAD

**Issue by njpatel54** [Azure/AzOps#550]
**Describe the bug**
I was able to deploy ESLZ to US Government cloud with GitHub integration. However, two issues I found so far after deployment  .... 

(1) Right after deployment when AzOps try to fetch current state of Azure, it fails. What I found is that **pull.yml** file does not use "**-environment AzureUSGovernment**" as part of **Connet-AzAccount** command.  So, pull.yml file need to be updated to correct this. (Side note - similar changes are needed for push.yml and validate.yml file as well)

(2) Whenever I tried to deploy new policy, it by default targets **location** as **northequrope**. In json template location is defined as **[deployment().location]**. I did not find any solution to resolve this issue. 

How can I resolve this?

**Steps to reproduce**

1.
2.

**Screenshots**
![policy assignment error](https://user-images.githubusercontent.com/26607717/151909836-cd090894-4185-493f-b26a-376bbfe12266.jpg)

**Comment by daltondhcp** [comment]
Thank you @jtracey93 and @njpatel54. 
AzOps is indeed supported in the sovereign clouds such as US Gov and Azure China. 
To solve the issue with deployment, you need to change the [setting](https://github.com/Azure/AzOps-Accelerator/blob/main/settings.json#L7) `Core.DefaultDeploymentRegion` that Jack pointed out to one of the [USGov supported regions](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-ps#get-current-regions), such as `usgovvirginia`.

We will use this issue to track creation of guidance for this. :)

**Comment by njpatel54** [comment]
Update - 

I just tested everything end-to-end works in Azure US Government. Couple of changes and it all works now. Changes made are 

(1) In "Action Secrets", I added "ARM_ENVIRONMENT" with value "AzureUSGovernment". 

(2) Edited pull.yml, push.yml and validate.yml file to include ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }} and then modified Connect-AzConnect commandline to include -Environment $env:ARM_ENVIRONMENT. 

(3) Edited settings.json file to include "Core.DefaultDeploymentRegion": "usgovvirginia",.

**Comment by daltondhcp** [comment]
Thank you for the update!

**Comment by njpatel54** [comment]
I just test the new updates to resolve this issue and I found one minor change that needs to be made .... 

(1) After **fresh ESLZ deployment** in **AzureUSGovernment** environment, when initial pull (**Enterprise-Scale Deployment**) occurs, it fails with following error.

![image](https://user-images.githubusercontent.com/26607717/153673930-8393b147-9374-4e5f-9e85-1ad7adf1fde3.png)

(2) I tracked down the **action.yml** file under **.github/actions/sharedSteps**. Looks like when following command carried out, it fails.

**(ConvertTo-SecureString -String ${{env.ARM_CLIENT_SECRET}} -AsPlainText -Force)**

What it seems that if this **en.ARM_CLIENT_SECRET** variable is passed on with **quotes** then it succeeds.
