### ISSUE TITLE
AzOps Pull-pipeline doesn't discover resource groups

### ISSUE THREAD

**Issue by egullbrandsson** [Azure/AzOps#555]
**Describe the bug**
Hi,

For some reason when I'm running the `Invoke-AzOpsPull -Rebuild`
I'm only getting some of the resource groups discovered in my subscriptions.

Anything you've seen before? Any tips on where to start troubleshooting?

**Comment by daltondhcp** [comment]
Hi @egullbrandsson,

This is not an issue that we have seen before. Can you share the settings from settings.json, specifically:
```       
"Core.SkipResource": 
"Core.SkipChildResource": 
"Core.SkipResourceGroup":
"Core.SubscriptionsToIncludeResourceGroups": 
```
Also, what permissions does the service principal have in the environment?

**Comment by egullbrandsson** [comment]
> Hi @egullbrandsson,
> 
> This is not an issue that we have seen before. Can you share the settings from settings.json, specifically:
> 
> ```
> "Core.SkipResource": 
> "Core.SkipChildResource": 
> "Core.SkipResourceGroup":
> "Core.SubscriptionsToIncludeResourceGroups": 
> ```
> 
> Also, what permissions does the service principal have in the environment?

Hi Johan,

The SPN I'm using have 'Owner'-permissions on a management group which we call 'CustomerRoot' and then it has 'Reader' on the actual root("/") scope.
As you can see in the settings.json below we're doing a PartialMgDiscoveryRoot.

This is what the settings-file looks like:

{
    "Version": 1,
    "DynamicTree": {
        "AzOps": {
            "Core.AutoGeneratedTemplateFolderPath": ".",
            "Core.AutoInitialize": true,
            "Core.DefaultDeploymentRegion": "westeurope",
            "Core.EnrollmentAccountPrincipalName": "",
            "Core.ExcludedSubOffer": [
                "AzurePass_2014-09-01",
                "FreeTrial_2014-09-01",
                "AAD_2015-09-01"
            ],
            "Core.ExcludedSubState": [
                "Disabled",
                "Deleted",
                "Warned",
                "Expired"
            ],
            "Core.ExportRawTemplate": false,
            "Core.IgnoreContextCheck": false,
            "Core.InvalidateCache": true,
            "Core.OfferType": "MS-AZR-0017P",
            "Core.PartialMgDiscoveryRoot": [
                "CustomerRoot"
            ],
            "Core.SkipPolicy": false,
            "Core.SkipResource": true,
            "Core.SkipResourceGroup": false,
            "Core.SkipResourceType": [
                "microsoft.alertsmanagement/smartDetectorAlertRules",
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "microsoft.visualstudio/account",
                "Microsoft.VSOnline/plans"
            ],
            "Core.SkipRole": true,
            "Core.SubscriptionsToIncludeResourceGroups": "*",
            "Core.TemplateParameterFileSuffix": ".json",
            "Core.ThrottleLimit": 10,
            "Core.WhatifExcludedChangeTypes":[]
        },
        "|AzureDevOps": {
            "!Condition": "EnvAzDevPipeline",
            "AzOps.Core.State": "%PIPELINE_WORKSPACE%/root"
        },
        "|GitHub": {
            "!Condition": "EnvGithubAction",
            "AzOps.Core.State": "%GITHUB_WORKSPACE%/root"
        },
        "PSFramework": {
            "Message.Info.Maximum": 3
        }
    }
}

**Comment by jsandquist** [comment]
Hi @egullbrandsson, what version are you using - 1.6.4? 1.7.2?

I would change to more verbose logging (9) and set the ThrottleLimit to 1 - maybe something like this:

```
    ...
    "Core.SkipChildResource": true,
    ...
    "Core.SubscriptionsToIncludeResourceGroups": [
        "platform-*",
        "landingzone-*",
    ],
    ...
    "Core.ThrottleLimit": 1,
    ...
    "Core.WhatifExcludedChangeTypes": [
       "NoChange",
       "Ignore"
    ],
    ...
"PSFramework": {
    "Message.Info.Maximum": 9
}
...
```

**Comment by egullbrandsson** [comment]
> Hi @egullbrandsson, what version are you using - 1.6.4? 1.7.2?
> 
> I would change to more verbose logging (9) and set the ThrottleLimit to 1 - maybe something like this:
> 
> ```
>     ...
>     "Core.SkipChildResource": true,
>     ...
>     "Core.SubscriptionsToIncludeResourceGroups": [
>         "platform-*",
>         "landingzone-*",
>     ],
>     ...
>     "Core.ThrottleLimit": 1,
>     ...
>     "Core.WhatifExcludedChangeTypes": [
>        "NoChange",
>        "Ignore"
>     ],
>     ...
> "PSFramework": {
>     "Message.Info.Maximum": 9
> }
> ...
> ```

Hi @jsandquist,

Thanks for the input!

I've tried both 1.7.1 and 1.7.2, did a troubleshooting session yesterday in a dev container locally with @daltondhcp and @SimonWahlin.
We didn't find the problem but we're still troubleshooting, will update the issue when we find something. :cowboy_hat_face:
