### ISSUE TITLE
Deployments/push fail with deployment already exists in location error

### ISSUE THREAD

**Issue by Freakling** [Azure/AzOps#558]
The FAQ references [an error with a workaround.](https://github.com/azure/azops/wiki/frequently-asked-questions#deploymentspush-fail-with-deployment-already-exists-in-location-error), however this should be able to be solved by adding a unique suffix to rg deployments.

Currently the -name parameter is not provided, but to allow redeployment and having a complete deployment history a unique id should be provided, I suggest either a concat of the file+unique salt for readability or just guid if readability is not a priority
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-7.2.0

**Comment by daltondhcp** [comment]
Thank you for the feedback!

Currently, we are generating our deployment names with the deterministic `AzOps-<FileName>` pattern and do indeed pass that on with the -Name parameter to the respective `New-Az*Deployment` cmdlets. 😄 

To overcome the issue in the FAQ, we have thought about adding the regional element to the deployment name. Would that help you in your scenario? 

Regarding generating unique deployment names for each push/deploy, we have currently decided to not implement that to avoid clutter in troubleshooting scenarios etc.

**Comment by Freakling** [comment]
For specifically ResourceGroupDeployments this could be a good solution, limited regions will decrease clutter.
