### ISSUE TITLE
Azure Gov Deloyment after recent update 

### ISSUE THREAD

**Issue by njpatel54** [Azure/AzOps#563]
[](https://user-images.githubusercontent.com/26607717/153673930-8393b147-9374-4e5f-9e85-1ad7adf1fde3.png)

After recent update (https://github.com/Azure/AzOps/pull/554), new deployment in Azure Gov fails.

(1) After fresh ESLZ deployment in AzureUSGovernment environment, when initial pull (Enterprise-Scale Deployment) occurs, it fails with following error.

![image](https://user-images.githubusercontent.com/26607717/154170746-997bc488-f147-4d2e-bf3e-2f08bf18d0b6.png)

(2) I tracked down the action.yml file under .github/actions/sharedSteps. Looks like when following command carried out, it fails.

(ConvertTo-SecureString -String ${{env.ARM_CLIENT_SECRET}} -AsPlainText -Force)

**Comment by daltondhcp** [comment]
Hello @njpatel54,
Thank you for reporting this. This is actually related to the spn secret that includes som special characters that we obviously shouldn't care about. (see below)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/16622613/154211130-2aa16780-c225-4d6d-a6cf-cd833532de47.png">

It has now been addressed in https://github.com/Azure/AzOps-Accelerator/pull/113. Please update line 63 in your pipeline as per https://github.com/Azure/AzOps-Accelerator/pull/113/files#diff-0266bec6c91e21387169965c5ea535cf169b74d32b487ae1d096f35e9918afd4R63
