### ISSUE TITLE
Simplify AZURE_CREDENTIALS secret

### ISSUE THREAD

**Issue by krowlandson** [Azure/AzOps#57]
The current AZURE_CREDENTIALS secret format includes the following fields which are not needed:

- displayName
- name
- subscriptionId

Whilst these could optionally be specified, they seem to just add unnecessary complexity when generating the AZURE_CREDENTIALS secret value.

This feature request is to remove the dependency on these values in [Azure/AzOps](https://github.com/Azure/AzOps) and to update documentation in [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale).

**Comment by irwins** [comment]
Hi,

I'm very much interested in this enhancement! I've been looking into how to rotate a spn secret and update the secret in github

For me its a learning process... The snippets are all in javascript. I finally figured out how the run them [gist](https://gist.github.com/irwins/03a735f23642c9bd87e3ea57697819bdl)

I would love to get a better understanding of the ins and outs of Github actions. Before visiting your repo I had no idea you could do so much and most of it  in PowerShell!!! Color me impressed!!! 

Rg.

**Comment by stefanstranger** [comment]
Hi Irwin,

Link to your gist does not returns the gist.

/Stefan

**Comment by irwins** [comment]
Fixed it! Thanks!
