### ISSUE TITLE
AzOps - Push pipeline - deployment failed with permissions error 

### ISSUE THREAD

**Issue by sarahjaneclark** [Azure/AzOps#574]
**Describe the bug**
The below error occurs with the push pipeline following the successful pull pipeline of the AzOps Accelerator run in Azure DevOps. This has only happened when there are changes to the AAD subscription. On the first occasion, all subscriptions updated successfully apart from this subscription. This change updated the location from current named region to [deployment().location].

New-AzManagementGroupDeployment: The deployment 'AzOps-microsoft.management.managementgroups-xxxxxxxxx' failed with error(s). Showing 2 out of 2 error(s). Status message: (Code:) Status Message: At least one resource deployment operations failed. Please list deployment operations for details. - (Code: DeploymentFailed)  - {  "error": {    "code": "BadRequest",   "message": "User does not have permission to view role assignments on subscription xxxxxxxxx", "details": "The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription." 

The SPN has been given privileges over the root management group and still has the directory readers role in AAD. 

Apologies I am new to AzOps and logging issues in GitHub. Please could you advise if this is expected behaviour? or where this change came from? Thanks

**Comment by daltondhcp** [comment]
Thank you for submitting the issue. 
Can you please elaborate on what changes you are trying to push? 
Also, if possible, can you share a correlationId from the failed push job?

**Comment by daltondhcp** [comment]
Closing as per offline conversation.
