### ISSUE TITLE
Authentication Failure for GitHub Enterprise Managed Users

### ISSUE THREAD

**Issue by autocloudarc** [Azure/AzOps#576]
**Describe the bug**

Customer using GitHub Enterprise Managed User could not authenticate with the org or username and their PAT specified from the CI/CD tab parameters.

**Steps to reproduce**

1. Deploy the vWAN scenario
2. Wait until the resources are deployed except for creating the GitHub repo 

**Screenshots**

Error message from the deployment activity in Azure.

... \"System.Management.Automation.RuntimeException: Failed to create repository\\r\\n{\\\"message\\\":\\\"Unauthorized: As an Enterprise Managed User, you cannot access this content\\\",\\\"documentation_url\\\":\\\[https://docs.github.com/rest/reference/repos#create-a-repository-using-a-template\\\](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Frest%2Freference%2Frepos%23create-a-repository-using-a-template%255C%255C%255C&data=04%7C01%7Cprestopa%40microsoft.com%7Cc589b15b8e01432a5b9108da014fbb05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637823739212421974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k3SrSaVRbtNCkCUK5zxsY8Cu0mf%2F%2FbwK9NHYc0Mt2MQ%3D&reserved=0)}\\r\\nat <ScriptBlock><Process>, /mnt/azscripts/azscriptinput/ARMAzOpsSetup.ps1: line 134\\r\\nat <ScriptBlock>, <No file>: line 1\\r\\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1

**Comment by daltondhcp** [comment]
This is a known limitation with Enterprise Managed Users, i.e. they cannot interact with public repositories like in this case, programmatically create a new repo based on a public template repo.
So, to overcome this, you need to follow instructions at https://github.com/azure/azops/wiki/github-actions to manually configure the repo/pipelines.  
<img width="942" alt="image" src="https://user-images.githubusercontent.com/16622613/157387078-6137add6-1f0a-4760-9224-77d968a0c7c8.png">
[About Enterprise Managed Users - GitHub Docs](https://docs.github.com/en/enterprise-cloud@latest/admin/authentication/managing-your-enterprise-users-with-your-identity-provider/about-enterprise-managed-users#about-enterprise-managed-users)[](https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d4-d82261a67752920cea3ce376e71521e1/views/imgo)

We will look into adding a note about this in the UX or in the FAQ.
