### ISSUE TITLE
Initialize-AzOpsEnvironment fails with incorrect file path error

### ISSUE THREAD

**Issue by plwhite** [Azure/AzOps#577]
**Describe the bug**

If I run `Initialize-AzOpsEnvironment` it fails with the following error.

~~~
WARNING: [09:49:47][Assert-AzOpsWindowsLongPath] Git has not been configured for long path support
WARNING: [09:49:47][Assert-AzOpsWindowsLongPath] Windows not sufficiently configured for long paths! Follow instructions for "Enabling long paths on Windows" on https://aka.ms/es/quickstart.
Initialize-AzOpsEnvironment: Windows not configured for long paths. Please follow instructions for "Enabling long paths on Windows" on https://aka.ms/es/quickstart.
~~~

The URL in question leads to a 404 error, so presumably this is a known issue with a workaround whose documentation has been lost. I've tried some likely things, but nothing has worked yet.

**Steps to reproduce**

1. Install AzOps
2. Try to run the initialize command.

**Workarounds**

None found, but if you could post how to resolve then that will unblock me while you fix the tooling / documentation.

**Comment by daltondhcp** [comment]
Hi,

Thank you for pointing out the broken link - we will fix that. The current doc for this that includes required steps if you want to run AzOps locally in windows is documented @ https://github.com/azure/azops/wiki/troubleshooting#windows.

**Comment by plwhite** [comment]
Thanks - I somehow missed those links, but they do cover exactly what I needed to do.

**Comment by daltondhcp** [comment]
Also note that while it works to run AzOps locally in Windows, it is mainly for debugging/troubleshooting purposes. 
To get the best end-to-end experience, I highly recommend setting up AzOps using the [Azure DevOps](https://github.com/azure/azops/wiki/azure-pipelines) or [GitHub Actions](
https://github.com/azure/azops/wiki/github-actions) starter pipelines.

**Comment by plwhite** [comment]
Yes, understood thanks. I'm just spending a couple of hours manually running things to learn about what the tools do, so that I have a better understanding of what those pipelines are actually doing and what they might mean for our customers.
