### ISSUE TITLE
Naming convention for templates at different scopes

### ISSUE THREAD

**Issue by rahul-ve** [Azure/AzOps#582]
Hi,

I couldn't find guidance on naming for the template files in the wiki, looks like it is relevant information to be documented somewhere.  Apologies if that info is present and I missed it. 
I deployed a new resource group using a shorter filename, `ms.resources_<rg_name>.json`. It deployed fine but later on the pull workflow added the same template with the long filename `microsoft.resources_resourcegroups-<rg_name>.json`.

And what about resources, are there any conventions we need to follow?

Thanks
rahul

**Comment by daltondhcp** [comment]
The autogenerated templates will follow the convention you mentioned. For custom templates, you can follow any convention you want. Do note that you can choose to stow away the autogenerated templates in a separate folder with the `AutoGeneratedTemplateFolderPath` setting. 
https://github.com/azure/azops/wiki/settings

**Comment by rahul-ve** [comment]
@daltondhcp 
Thanks for the clarification.
