### ISSUE TITLE
Secret Variables and Parameters not following best practices

### ISSUE THREAD

**Issue by mjrich19** [Azure/AzOps#583]
**Describe the bug**
The Azops Accelerator is not following Microsoft's recommendation with regard to passing secret parameters and secret variables to scripts. 

[Documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)

**Example**

In 'sharedsteps.yml' the parameters with secret information such as '$(ARM_CLIENT_SECRET)' are passed directly to the host console on line 87. This is a problem because an operating system which logs the console will capture those secrets. Microsoft's recommendation is to map the secret parameters/variables to environment variables on the host console that way any console logs will only capture the environment variable name.

**Comment by daltondhcp** [comment]
Thank you for reporting @mjrich19 - it should hopefully be an easy fix since we moved over to templates and only use refer to the SPN secret in one pipeline. 
When it comes to self-hosted agents, @StefanIvemo are working on publishing some guidance around that (tracked in #548)
