### ISSUE TITLE
Reconsider naming conventions, hitting 255 char limit on NTFS

### ISSUE THREAD

**Issue by rahul-ve** [Azure/AzOps#585]
Hi team,

We used the hub & spoke (adventureworks) template to provision our Azure platform and it worked pretty well, one suggestion we have is to reconsider the naming of the high-level folders, they are too long. With the current implementation, it leaves very little room for naming resources before hitting the filename length limitations. We are hitting the 255 char limit on NTFS. We did not notice this issue initially due to most of us using WSL /ext4. 

e.g., below is generated by the accelerator template, and is 237 chars long, we are using the root of the filesystem to alleviate the situation.  The only thing in there we configured was the subscription name following MS docs/recommendations. 

Is there a setting we missed? or how are others managing this issue. 

```
root/eslz (eslz)/eslz-platform (eslz-platform)/eslz-connectivity (eslz-connectivity)/sub-it-conn-hub-001 (23f8d265-7108-4dfe-ba89-f46aee1697ab)/eslz-vnethub-australiaeast/microsoft.resources_resourcegroups-eslz-vnethub-australiaeast.json
```

Thanks
Rahul

**Comment by rahul-ve** [comment]
Thanks @uday31in, will test it tomorrow and get back to you. 
There is still a lot of redundancy in the folder names and working in the repo is very cumbersome with such long names. Just my feedback from the short time I have used this implementation. 
We still think it is  the best IaC implementation, Thanks for the great work!

**Comment by uday31in** [comment]
Unfortunately there is no easy solution for this because subscription names in a Tenant are not unique and using GUIDs are non-intuitive at-scale.

Thank you for the feedback and appreciation.

**Comment by rahul-ve** [comment]
@uday31in 
Enabling long filenames worked perfectly.
