### ISSUE TITLE
Azure policy exemptions at resource level are not exported

### ISSUE THREAD

**Issue by MM-MikeM** [Azure/AzOps#588]
**Describe the bug**
After creating a policy exemption at the resource level using the Azure portal the new exemption does not appear in the GitHub repository as a new json file after a AzOps - Pull. The repository is unchanged after the pull.

**Steps to reproduce**

1 .Create a policy exemption for an Azure policy assignment using the Azure portal
2. Run the AzOps -Pull workflow

**Screenshots**

**Comment by daltondhcp** [comment]
Sorry for the delayed response and thank you for the feedback
We currently don't support pulling exemptions at that scope - we will take a look at adding as an enhancement it in a future release.

**Comment by daltondhcp** [comment]
In the [1.7.6](https://github.com/Azure/AzOps/releases/tag/1.7.6) release, we added support for this at resourceGroup scopes. However, due to manageability concerns with excemptions at a resource level, we have decided not to implement support for this.
