### ISSUE TITLE
Add option to specify deployment order

### ISSUE THREAD

**Issue by StefanIvemo** [Azure/AzOps#592]
**Describe the solution you'd like**

If I commit multiple templates at once the current behavior of AzOps is to create deployments in alphabetical order based on my template names. I would like to have the possibility to specify a custom deployment order within a scope by adding a `.order` file or something similar. 

***.order example:**
```
ipprefix.bicep
publicIp.bicep
azureFirewall.bicep
```

There are a couple of use-cases that we have stumbled upon where this would be really nice to have. Our current workaround is to name our templates with a number prefix to control the deployment order.

**Comment by daltondhcp** [comment]
As discussed offline yesterday, the implementation approach will be as follows:
- [ ] Remove `Sort-Object` from deployment logic in [Invoke-AzOpsPush](https://github.com/Azure/AzOps/blob/main/src/functions/Invoke-AzOpsPush.ps1) to honor deploymentlist ordering
- [ ] Add additional step in validate-deploy pipeline to handle **optional** ordering at different scopes
