### ISSUE TITLE
Manually trigger `Push` pipeline and specify scope to deploy

### ISSUE THREAD

**Issue by StefanIvemo** [Azure/AzOps#593]
**Describe the solution you'd like**

A customer of ours that are using AzOps requested the possibility to trigger a re-deploy of templates without forcing a git diff, for example by adding a comment to a template and open a pull request. One scenario could be that they want to re-deploy all resources in a resource group. What they want is to be able to trigger the push pipeline and specify a scope, RG or subscription, and then force a push of all the templates in that scope at once.

**Comment by daltondhcp** [comment]
As discussed offline, this will be implemented with a separate push pipeline that can only be triggered manually accepting deploymentscope as input (managementGroup -> subscription -> resourceGroup -> resource/individual template)
