### ISSUE TITLE
Bug Report: `Core.IncludeResourcesInResourceGroup` setting not working as expected

### ISSUE THREAD

**Issue by matthewponzio** [Azure/AzOps#619]
**Describe the bug**
I have the following configuration in my `settings.json`
```json
"Core.IncludeResourcesInResourceGroup": ["cloud-eng-network"],
```
I would expect that the Pull pipeline would then ONLY discover Resources in Resource Groups named `cloud-eng-network`

However, when I add Resources to Resource Groups OTHER THAN `cloud-eng-network`, they are still being discovered.

**Steps to reproduce**

1. Create a Resource Group named `cloud-eng-network`
2. Create a Resource Group named `<your_choice>`
3. Configure `"Core.IncludeResourcesInResourceGroup": ["cloud-eng-network"],` in `settings.json`
4. Add any Resource to each of the two Resource Groups
5. Run the Pull pipeline
6. Notice that BOTH Resources are discovered -- instead of ONLY the Resource within the `cloud-eng-network` Resource Group

**Screenshots**
![image](https://user-images.githubusercontent.com/21246142/167480629-c5521d60-b552-42f3-8541-8c81d7c4d82a.png)

<img width="1118" alt="Screen Shot 2022-05-09 at 3 12 23 PM" src="https://user-images.githubusercontent.com/21246142/167480959-e603cfde-ad09-45b4-a1d3-99fa06910bdb.png">

<img width="1118" alt="Screen Shot 2022-05-09 at 3 13 22 PM" src="https://user-images.githubusercontent.com/21246142/167481093-304ba9bd-27c2-4905-959a-47900ba62319.png">

![Screen Shot 2022-05-09 at 3 15 13 PM](https://user-images.githubusercontent.com/21246142/167482414-91db3b1e-1545-4b62-9c43-3683574b215a.png)

**Comment by daltondhcp** [comment]
Thank you for raising this. Maybe I wasn’t very clear around this in the question you asked under discussions. That feature is introduced in #609, but we haven’t cut a release for it yet. Targeting for 1.8.0 in a week or so. 

Apologies for the inconvenience.

**Comment by matthewponzio** [comment]
@daltondhcp Oh my...of course..derp.  I spent a bunch of time reading through the code to see if maybe I was misunderstanding the intent of the feature..and I'm like yeah, it looks like it's all set up to work like I understood?!  But then...I'm looking at my cloned copy of `master` ...and not 1.7.7.  Ugh. 🙄  I didn't actually think it was a bug, but it seemed more appropriate to bring it up there than in Discussions.  Anyway, thanks again for the reply.  You definitely saved me some additional head scratching today!
