### ISSUE TITLE
Bug Report - Incorrect GitHub Actions permissions for IaC repo based on AzOps-Accelerator template repo

### ISSUE THREAD

**Issue by rahul-ve** [Azure/AzOps#620]
**Describe the bug**

When using [AzOps](https://github.com/Azure/AzOps) template repo, the default **Workflow permissions** settings might not be correct. 
The default setting are set to read for all scopes:
![image](https://user-images.githubusercontent.com/29165428/168426171-0036ad9e-445f-4d52-b3c5-4d337d4e473e.png)

Tested using the [adventureworks accelerator template](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md), the first pull action fails with:

```
Run git push origin automated -f 
remote: Write access to repository not granted. 
fatal: unable to access ' https://github.com/rahul-ve/eslzxx/': The requested URL returned error: 403 
Error: Process completed with exit code 128.

```
I  played around with the permissions on different scopes, this changed the error to:

```
Run gh pr create --title "Automated State" --body "-" --base 'main' --head automated 
pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest) 
Error: Process completed with exit code 1.
```
I used below permissions based on [this file sample workflow](https://github.com/Azure/AzOps-Accelerator/blob/34efdb9d453f257cc213d4ecfdd8864bdcdf8db4/.github/samples/oidc-azuread/pull.yml#L48):

```
permissions:
  id-token: write
  contents: write
  pull-requests: write
```
Above error was resolved after checking  the option **"Allow GitHub Actions to create and approve pull requests"**.
This option cannot be enabled if it is disabled at the GitHub organization level. [This change was introduced recently](https://github.blog/changelog/2022-05-03-github-actions-prevent-github-actions-from-creating-and-approving-pull-requests/) to plug a security issue. 

I looked at one of the previous deployments and the workflow settings there were:
![image](https://user-images.githubusercontent.com/29165428/168426244-aeb325c0-7b89-4100-adb6-1b3ae676c2a2.png)

**Steps to reproduce**

1.  Use the [adventureworks accelerator template](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md) to deploy
2. First pull should fail with permission issues.

The [AzOps GitHub Actions wiki](https://github.com/Azure/AzOps/wiki/GitHub-Actions)  page might be missing some details. 

Thanks
Rahul

**Comment by daltondhcp** [comment]
Thank you for reporting this and indeed, it is related to the tightened default security settings for orgs/repos. We will make sure to update docs accordingly
