### ISSUE TITLE
Pull action failed in the Workflow

### ISSUE THREAD

**Issue by Divyasri199** [Azure/AzOps#624]
In [Excercise 1> Task 2> Step 8](https://github.com/CloudLabsAI-Azure/AVW-Cloud-Adoption-Framework/blob/stage/Instructions/01.md#task-2-validation-post-deployment), the pull action got failed with the error mentioned below.

 git push origin automated -f
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ARM_CLIENT_ID: ***
    ARM_CLIENT_SECRET: ***
    ARM_ENVIRONMENT: 
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    AZOPS_MODULE_VERSION: 
    GITHUB_TOKEN: ***
    modulesFolder: ~/.local/share/powershell/Modules
    folder: root
    branch: automated
    commit_message: Automated commit
    pull_request: Automated State
    MODULE_VERSION: 1.7.7
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/divyasri1999/eslz/': The requested URL returned error: 403
Error: Process completed with exit code 128.

![image](https://user-images.githubusercontent.com/83349577/168613511-45314d28-cf3c-4b3c-8790-08947851e111.png)

**Comment by daltondhcp** [comment]
Thank you for reporting, we are aware and solution can be found in #620. We push doc updates a.s.a.p.
