### ISSUE TITLE
Running "AzOps - Push" - "Principal 74c26a0ce2d047daaf3824f96f607986 does not exist in the directory"

### ISSUE THREAD

**Issue by WernerRall147** [Azure/AzOps#633]
When Running "AzOps - Push" as it gets to Deploy step I get the below error. I cannot seem to find where that principal ID comes from as it wasn't something I created?

New-AzManagementGroupDeployment: 15:51:17 - The deployment
'AzOps-microsoft.authorization_roleassignments-2fe83f5e-4e64-B9EE' failed with
error(s). Showing 1 out of 1 error(s). Status Message: Principal
74c26a0ce2d047daaf3824f96f607986 does not exist in the directory
xxxxxxxxxxxxxxxxxxxxxxxxxxx. Check that you have the correct principal
ID. If you are creating this principal and then immediately assigning a role,
this error might be related to a replication delay. In this case, set the role
assignment principalType property to a value, such as ServicePrincipal, User,
or Group.  See https://aka.ms/docs-principaltype (Code:PrincipalNotFound) 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/23274490/169349203-26bbdcc0-4899-41f2-97da-b73ff62fc9a9.png">

**Comment by daltondhcp** [comment]
Did this happen after your initial AzOps-Pull, or did you specifically deploy the failing roleAssignment manually? 
The error typically happens when "stale" roleAssignments originating from policyAssignments are pulled back and then pushed back to the platform. 
If you look at the particular scope in the portal, you will likely find an "unknown" roleAssignment.

**Comment by WernerRall147** [comment]
Thanks @daltondhcp for your super fast response. It was after my initial Push. Your suggestion guided me in the right direction and after I followed some similar steps using PowerShell to find and remove all unknown assignment-->
https://jloudon.com/cloud/Removing-Unknown-Azure-RBAC-Role-Assignments-with-PowerShell/ 
All pipelines now execute successfully!

**Comment by daltondhcp** [comment]
Thank you for reporting back!
