### ISSUE TITLE
AzOps - Pull failing on AzOps 1.8.0

### ISSUE THREAD

**Issue by CerveloRS** [Azure/AzOps#639]
AzOps - Pull pipeline was running withouth the version parameter set and started failing when 1.8.0 became the latest release.

**Steps to reproduce**

1. Run AzOps - Pull pipeline with version 1.8.0 of AzOps module.

**Screenshots**
![image](https://user-images.githubusercontent.com/85163705/170099431-869347c3-6062-4f90-8a02-44945b298a85.png)

**Workaround**
Force AzOps - Pull pipeline to use version 1.7.7

**Comment by daltondhcp** [comment]
Thank you for reporting this. Can you please share your settings.json file as well as execution environment (GitHub actions/Azure DevOps) and if you are using self-hosted runners?

**Comment by CerveloRS** [comment]
- Settings.json attached.
- Environment: Azure Devops
- Not using self hosted

[settings.zip](https://github.com/Azure/AzOps/files/8765304/settings.zip)

**Comment by Jefajers** [comment]
Thanks for your quick reply, we are looking into it.

We are able to reproduce this when Core.PartialMgDiscoveryRoot is set.

**Comment by CerveloRS** [comment]
Thank you!

**Comment by daltondhcp** [comment]
Thank you for reporting this @CerveloRS - this is now fixed in our 🚒 release [1.8.1](https://github.com/Azure/AzOps/releases/tag/1.8.1). 
Please let us know if something isn't working as expected.

**Comment by CerveloRS** [comment]
Thank you. Confirmed working on my end aswell.
Great work :)
