### ISSUE TITLE
AzOps - Pull fails with MissingApiVersionParameter

### ISSUE THREAD

**Issue by CerveloRS** [Azure/AzOps#644]
**Description**

When running AzOps - Pull to get all policies, resources, resourcegroups, and roles on two managementgroups (and whatever is below), the pipeline fails on step **Initialize** with following error (some information replaced with replaced):

`[06:32:35][Get-AzOpsRoleAssignment] Retrieving Role Assignments at scope /subscriptions/replaced/resourceGroups/replaced
WARNING: [06:33:55][Invoke-AzOpsScriptBlock] Tried unsuccessfully 6 out of 6 times, giving up. | MissingApiVersionParameter : The api-version query parameter (?api-version=) is required for all requests.
CorrelationId: 95e29d50-26aa-445e-b4e0-15a538da9302
Exception: The running command stopped because the preference variable
`

**Steps to reproduce**

1. Run AzOps Pull with attached settings.

AzOps Module version 1.8.1

[settings.json.zip](https://github.com/Azure/AzOps/files/8784546/settings.json.zip)

**Comment by daltondhcp** [comment]
Looks like a transient issue in ARM, did it ever work before or did it start after a specific configuration change?

**Comment by daltondhcp** [comment]
After taking a closer look in the backend, it looks like it is failing on some `Microsoft.Web/certificates` resources that you have in some of your resource groups. Can you please try and add `Microsoft.Web/certiticates` to the `"Core.SkipResourceType"` array in settings.json and try again?

**Comment by CerveloRS** [comment]
It is not transient. The error always occurs on the same resourcegroup at:

`Retrieving Role Assignments at scope /subscriptions/replaced/resourceGroups/replaced`

**Comment by daltondhcp** [comment]
The roleAssignments message is unfortunately misleading, it is failing on what I mentioned above according to the correlationid.

**Comment by CerveloRS** [comment]
It does look similar. 
Added the exclusion. Now failing with correlationId 53f82858-a440-4300-8e15-94af477d66f0.
Please advise in troubleshooting the correlationids.

**Comment by daltondhcp** [comment]
The correlationIds are only for backend ARMlogs investigation, so unfortunately not something you can do on your own. We will investigate and look at a more graceful way to handle such resource provider failures. 
In the meantime, you can disable resource discovery to restore  pull operations without resources in RGS (except for roles and policies)

**Comment by CerveloRS** [comment]
Sadly the purpose of this repo and pipeline is to fetch the resources (as a backup of resources not deployed as code), but I will try some more exclusions and see if I get there.

**Comment by daltondhcp** [comment]
> It does look similar. Added the exclusion. Now failing with correlationId 53f82858-a440-4300-8e15-94af477d66f0. Please advise in troubleshooting the correlationids.

The above correlationId is interestingly enough related to the same resource type (`Microsoft.Web/certificates`). Can you double check spelling etc? 

Nevertheless, we will look at changing the way we handle these types of failures and instead throw a warning for child/auxiliary resources that cannot be exported.

**Comment by CerveloRS** [comment]
Spelling was fine. 

Warning rather then fail would be a welcome change.
Maybe even as a setting so one can choose to fail or warn?
