### ISSUE TITLE
Add lint and validate in AzOps

### ISSUE THREAD

**Issue by bengeset96** [Azure/AzOps#645]
**Describe the solution you'd like**

Would it be possible to add lint and validate cmdlets in validate-deploy.yml for Bicep files with AzOps?

![image](https://user-images.githubusercontent.com/99641908/170764443-7bfe3334-b0ab-44c5-b9a2-52f21a6c0e9b.png)
1. Seems to be taken care of based on source code, but should be in the right order.
2. Will help to check whether template is likely to deploy successfully. Will require communcation to Azure.  `Test-AzResourceGroupDeployment`
3. Seems to be taken care of based on source code. 
4. Obviously.
5. N/A for this feature request.

/b

**Comment by daltondhcp** [comment]
Thank you for the feedback.
On 1), for various reasons, we have deliberately decided not to do linting as part of the module (except for the warning messages that we get from bicep build). However, there is nothing preventing you from adding an additional step with for example https://github.com/Azure/PSRule.Rules.Azure in validate-deploy.yml to do more proper linting. 
On 2), `Get-Az*DeploymentWhatIfResult` that we run as part of the validate pipeline, actually takes care of 2 and 3 in one go in the following order `Template Validation -> Authorization (Permissions) -> WhatIf Results`. Hence, we se no reason to add an additional `Test-Az*Deployment` to the workflow.

**Comment by SimonWahlin** [comment]
If I don't misunderstand you, this is essentially what the validate pipeline does.

We don't lint and validate as separate steps, but we are doing a what-if deployment which includes step 1-3.

How would you like the experience to be?

**Comment by bengeset96** [comment]
@daltondhcp @SimonWahlin 

Thank you both for such quick response. 

1. Bicep build is what I define as linting as it contains predefined set of rules for several categories like unused parameters, string interpolation, default values for secure parameters etc. This is also done in preflight validation.

I am already using PSRule with AzOps in the validate-deploy.yml for making sure that code base is alligned with WAF, but I understand well that this has not been implemented as there is no one size fits all.

2. Great, I was not aware it is already taken care off, that is just fantastic. 

Consider my feature request as not reading source code good enough before applying something that is nonsense. 

Is it `New-AzOpsDeployment.ps1` that takes care of this?

Again thank you both for taking the time to answer me, it helps alot when documenting the solution that will of course be used on many customers.

/b

**Comment by daltondhcp** [comment]
Correct, it is done in New-AzOpsDeployment https://github.com/Azure/AzOps/blob/main/src/internal/functions/New-AzOpsDeployment.ps1#L136.
