### ISSUE TITLE
Resource Group Lock (Microsoft.Authorization/locks) resources cannot be Pull'd

### ISSUE THREAD

**Issue by mikewo-dc** [Azure/AzOps#662]
**Describe the bug**

No ARM template is ever Pull'd by AzOps for Microsoft.Authorization/locks resource created at Resource Group scope. Push for an ARM template for Microsoft.Authorization/locks resource at Resource Group scope works correctly, but Pull doesn't work for resource whether created in portal or via AzOps.

**Steps to reproduce**

1. Create a Resource Group
2. Create a "CanNotDelete" Lock on the resource group
3. Do a Pull into AzOps repository - no "Microsoft.Authorization/locks" resource appears

**Screenshots**

![image](https://user-images.githubusercontent.com/99307319/174940066-5365e60e-fb68-46f9-bb57-18570eb642d0.png)

![image](https://user-images.githubusercontent.com/99307319/174940547-5a677897-1eb1-4c7f-a760-db0431f60e36.png)

**Comment by Jefajers** [comment]
Hi @mikewo-dc thanks for voicing your need.

The behaviour you describe in regard to the resource-type `Microsoft.Authorization/locks` not being pulled back by AzOps is correct and expected at this time, support for pulling back that resource-type has not been added yet.

Based on your ask here I will make sure that we investigate the addition of `Microsoft.Authorization/locks` into AzOps future releases.

**Comment by mikewo-dc** [comment]
> The behaviour you describe in regard to the resource-type `Microsoft.Authorization/locks` not being pulled back by AzOps is correct and expected at this time, support for pulling back that resource-type has not been added yet.

Thank you very much - would you mind pointing me towards where I could learn which resource types are supported?

**Comment by daltondhcp** [comment]
We currently do not maintain a complete, updated list of supported resources providers. 
See following page for list of supported platform (proxyOnly) resources. https://github.com/azure/azops/wiki/introduction#discovery 
When it comes to tracked resources deployed in resource groups, we will export everything on a best effort basis.
