### ISSUE TITLE
Bug Report: Failure due to invalid characters

### ISSUE THREAD

**Issue by PleaseStopAsking** [Azure/AzOps#671]
**Describe the bug**
When attempting to pull our existing tenant along with all resources and child resources, the pull action fails with the following error.

```
The specified AzOpsState file contains invalid characters (remove any "[" or "]" characters)! Skipping /home/runner/work/super-octo-bassoon/super-octo-bassoon/root/tenant root group (***)/contoso (contoso)/management (management)/aa_main_master (***)/mgmt/./microsoft.insights_metricalerts-test-datasource [mcaafunctionsv1] failure detected.json
```

The resourceId of the resource it is failing on is `/subscriptions/redacted/resourceGroups/MGMT/providers/microsoft.insights/metricAlerts/Test-DataSource [mcaafunctionsv1] Failure Detected` and it is just an alert setup against a function to detect if the function fails execution. I have a few of these but this is the first one AzOps encounters.

**Steps to reproduce**

1. Setup Azure Function and configure it to an application insights resource
2. Enable alert for failed function invocations within the app insights resource
3. Make sure your AzOps settings are configured to pull resources and child resources
4. Run AzOps pull

**Comment by daltondhcp** [comment]
This is currently a known limitation as described in https://github.com/azure/azops/wiki/frequently-asked-questions#subscriptions-or-resources-not-showing-up-in-repository.

**Comment by PleaseStopAsking** [comment]
@daltondhcp Any comment on my previous note?

**Comment by bengeset96** [comment]
@PleaseStopAsking 

I've started to encounter the problem on various AzOps installations and since the names are pre-defined I see no other option than excluding for now. Temporary dirty fix.
