### ISSUE TITLE
AzOps setup fails with "Failed to create secrets myorg. Cannot bind argument to parameter 'PublicKey' because it is null."

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/AzOps#672]
**Describe the bug**

AzOps setup fails due to no public key existing on the repo it creates. Not sure where this public key would come from if the AzOps script isn't creating one itself, but it doesn't appear to. The script bails out if the repo already exists, so it doesn't seem that I can create a public key and then run it again.

**Steps to reproduce**

1. Run UI based Landing Zone Accelerator with AzOps enabled
2. Fails on azops-GitHub deployment script.

**Screenshots**

**Comment by joshuadmatthews** [comment]
Are you saying that    

$GitHubPublicKey = Invoke-GHRequest @BaseGHRest -Path "/actions/secrets/public-key" -Method Get
 
should create a public key? It seems the documentation says it gets a public key, and apparently that is returning null. I will try it on my own and see what happens, but I suspect I will get the same null.

**Comment by jtracey93** [comment]
Hey @joshuadmatthews, no sorry. Im asking if you are able to get it to return the public-key of the repo that is used to encrypt secrets.

**Comment by joshuadmatthews** [comment]
Yes if I run 

```
gh api \
  -H "Accept: application/vnd.github+json" \
  /repos/OWNER/REPO/actions/secrets/public-key
```

It is returning a public key

**Comment by jtracey93** [comment]
Maybe however, there is a check for this: https://github.com/Azure/AzOps/blob/main/scripts/ARMAzOpsSetup.ps1#L121-L122

Could you try again?

> You can also setup AzOps after the ALZ deployment by following: https://github.com/azure/azops/wiki/github-actions

**Comment by joshuadmatthews** [comment]
Yeah I saw that too, looks like it just checks if the repo exists, which it does. It's the public key that seems to not exists at the time it is asked for. 

I may go ahead and set it up manually, thanks for the link. Would be nice though to see it work from the deployment, not sure if there are any tasks that need to happen after that I'm not getting to because the deployment fails.

**Comment by daltondhcp** [comment]
Thanks for reporting @joshuadmatthews!

After a couple of runs I have been able to reproduce the issue and it indeed seems like it is related to eventual consistency. 
We will add an additional check to ensure it works every time.

**Comment by joshuadmatthews** [comment]
You guys rock! Thanks for following up.

**Comment by daltondhcp** [comment]
Hey @joshuadmatthews, 

Another thing before I open a PR for the updated version of the script, can you please verify that you added "admin:public_key" to your PAT token permissions? 
![image](https://user-images.githubusercontent.com/16622613/182166208-abcbb44b-286c-4f55-9a53-b6495a57d388.png)

Thanks,
Johan
