### ISSUE TITLE
Template specs versions are not skipped albeit mentioned in "Core.SkipResourceType"

### ISSUE THREAD

**Issue by gbeaud** [Azure/AzOps#694]
**Describe the bug**

In settings.json, I have added template specs versions in Core.SkipResourceType so versions are not extracted as code (see below). However, I still see template spec versions being extracted in the code.

            "Core.SkipResourceType": [
                "microsoft.alertsmanagement/smartDetectorAlertRules",
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "microsoft.visualstudio/account",
                "Microsoft.VSOnline/plans",
                "Microsoft.Resources/templateSpecs/versions"
            ],

**Steps to reproduce**

1. Add  "Microsoft.Resources/templateSpecs/versions" the SkipResourceType in settings.json
2. Create a template spec with 2 versions
3. Run AzOps including the resource group that contains the template spec versions
4. Look at the JSON files extracted and see that you have template specs versions

**Screenshots**

**Comment by Jefajers** [comment]
Hi gbeaud, I have had a look at the scenario, and I am unsuccessful in re-creating the scenario described. Could you confirm if I have misunderstood the scenario somehow or if this works for you as well on latest version of AzOps?

_Tests performed with AzOps version 1.9.1_

When I create a `Template spec` resource it is shown in the Azure portal properties as of type `Microsoft.Resources/templateSpecs`.

The specific versions of each `templateSpecs` is an ancillary resource of type `Microsoft.Resources/templateSpecs/versions`.
![image](https://user-images.githubusercontent.com/64077181/202873103-d3847013-421d-47d2-8c10-418fdc9b6924.png)


When running a pull with the following configuration:
`"Core.SkipResourceType": [
	"Microsoft.Resources/templateSpecs/versions"
]`

![image](https://user-images.githubusercontent.com/64077181/202873438-6d92f331-5ad1-468d-b8a5-be98c84a10d3.png)
The export contains the `Microsoft.Resources/templateSpecs` resource and no ancillary resources as expected.

If running it again with the following configuration:
`"Core.SkipResourceType": [
	"Microsoft.Resources/templateSpecs"
]`

![image](https://user-images.githubusercontent.com/64077181/202873506-eae7b3cb-f641-4d40-9d86-46759a63cc3d.png)
The export contains ancillary resources `Microsoft.Resources/templateSpecs/versions` and no `Microsoft.Resources/templateSpecs` resource as expected.

If I don’t want any of the two resource types I configure the setting in this way:
`"Core.SkipResourceType": [
	"Microsoft.Resources/templateSpecs",
"Microsoft.Resources/templateSpecs/versions"
]`

![image](https://user-images.githubusercontent.com/64077181/202873582-dc90c7bb-2df7-459c-a230-85304caadbe8.png)
The export does not contain any of the two resource types as expected.

**Comment by daltondhcp** [comment]
Hi @gbeaud - did Jespers answer above explain the behavior?

**Comment by Jefajers** [comment]
Closing for now, let us know @gbeaud if you still have a issue, then we can open it again 🚀.
