### ISSUE TITLE
Some filenames in the root/tenant folder are too long to be cloned/pulled locally

### ISSUE THREAD

**Issue by gbeaud** [Azure/AzOps#695]
**Describe the bug**

There is an issue when cloning/pulling the repo in VSCode/Terminal; some filenames in the root/tenant folder are too long! : error: unable to create file root/tenant root group (XYZ)/microsoft azure sponsorship 2 (XYZ)/rg-avd-weu-alz-storage/microsoft.resources_templatespecs_versions-ts-rg-avd-weu-alz-storage_rg-avd-weu-alz-storage_2022-10-03-18-05.json: Filename too long

error: cannot stat 'root/tenant root group (XYZ)/quorum (contoso)/platform (platform)/connectivity (connectivity)/connectivity (hub) subscription (XYZ)': Filename too long

**Steps to reproduce**

1. Give a really long name to one of your Azure resources, e.g. "ts-rg-avd-weu-alz-storage_rg-avd-weu-alz-storage"
2. Run an extract of the resources as code
3. Try to pull the repo locally

**Screenshots**

**Comment by StefanIvemo** [comment]
Have you enabled long paths in Windows? https://github.com/azure/azops/wiki/troubleshooting#windows

**Comment by daltondhcp** [comment]
Closing this issue for now as it should be resolved by following instructions in the previous response. 
Feel free to reopen if it's not resolved.
