### ISSUE TITLE
Node.js 12, set-output and save-state is deprecated in Github Actions

### ISSUE THREAD

**Issue by ole-bkk** [Azure/AzOps#696]
**Describe the bug**

The workflows provided by [Azure/AzOps-Accelerator](https://github.com/Azure/AzOps-Accelerator) is using actions and functions that is deprecated and will be disabled soon. 

More information:
- Node.js 12 is deprecated: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- 'set-output' and 'save-state' is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

As a current user of AzOps I`m not sure how to best handle this. Should we update our own workflows or can we for instance pull updated versions of the workflows provided in AzOps-Accelerator?

**Steps to reproduce**

Run either of the following workflows in Github Actions:
- 'AzOps - Pull'
- 'AzOps - Push'
- 'AzOps - Validate'

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/67264898/197127037-0781eaa7-7f4d-4182-b78a-926df9b3c380.png)

**Comment by daltondhcp** [comment]
Thank you for raising this. It is certainly on our radar and we will update the starter accelerator pipelines a.s.a.p. 

For existing customers, we will add some guidance in our FAQ - but in short, the recommendation will be to update this manually in the pipelines.
