### ISSUE TITLE
Feature request: settings.json - resource group filter to support wildcard

### ISSUE THREAD

**Issue by jsandquist** [Azure/AzOps#697]
**Describe the solution you'd like**
In `settings.json` we have a few filters for:
 * subscriptions
 * resource groups
 * resource types

with some good examples in the [FAQ](https://github.com/azure/azops/wiki/frequently-asked-questions#discovery-scenarios-and-settings) :-)

I would like to see the resource groups filter to support wildcards just like the subscriptions filter - and hope to issue a PR for this soon.

Is this a good idea? Thoughts?

---

Subscription filter used at https://github.com/Azure/AzOps/blob/4eff6cb788892a41cf57c1166d754777d99cb1cc/src/internal/functions/Get-AzOpsResourceDefinition.ps1#L279

Resource group filter at
https://github.com/Azure/AzOps/blob/4eff6cb788892a41cf57c1166d754777d99cb1cc/src/internal/functions/Get-AzOpsResourceDefinition.ps1#L364

Tests would need to be updated as well.

**Comment by daltondhcp** [comment]
Hey @jsandquist - sounds reasonable to align the filtering supported at different scopes. Are you willing and able to take a stab at this yourself? 

Thanks,
Johan

**Comment by jsandquist** [comment]
Wow - a bit rusty apparently but eventually a PR will end up here in the proper repo 😆
