### ISSUE TITLE
Updating Settings.json and Pull pipeline fails.

### ISSUE THREAD

**Issue by BoostSebastian** [Azure/AzOps#699]
Updating Setting.json and Pull pipeline fails.

Using latest files from repo and tried to specify to use 1.9 of AzOps.

When going from setting.json:
```
            "Core.SkipPim": true,
            "Core.SkipPolicy": false,
            "Core.SkipResource": true,
            "Core.SkipChildResource": true,
            "Core.SkipResourceGroup": false,
```
to
```
            "Core.SkipPim": true,
            "Core.SkipPolicy": false,
            "Core.SkipResource": false,
            "Core.SkipChildResource": true,
            "Core.SkipResourceGroup": false,
```
or
```
            "Core.SkipPim": true,
            "Core.SkipPolicy": false,
            "Core.SkipResource": false,
            "Core.SkipChildResource": false,
            "Core.SkipResourceGroup": false,
```
I end up with the following error message and can't work around it:
```
Where-Object: The term 'Where-Object' is not recognized as a name of a cmdlet, function,
script file, or executable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
```

It is always stopping at Initialize step but at different amount of time, all from 4 minutes to 10 minutes
**Steps to reproduce**

1. Can't reproduce, happends everytime I try to redo the steps.

![steps](https://user-images.githubusercontent.com/24891371/200584735-e0a54e30-bb7f-4795-827e-dfb698e0690b.png)

**Comment by daltondhcp** [comment]
Hi Sebastian, 

Just tried in my own environment with the same settings and are unable to reproduce the issue. Have you made any other changes to the settings file? Can you share some more context on at what resource/scope it is trying to discover when it fails?

/Johan

**Comment by bengeset96** [comment]
Same here. In general getting a lot of different exceptions on the `Initialize` task. Different errors and different timespans. Happends on most of the `AzOps` installations.

![image](https://user-images.githubusercontent.com/99641908/200812678-f7c3e21b-e6d2-420a-8c71-d9a252c11181.png)

![image](https://user-images.githubusercontent.com/99641908/200811230-dcfdd18d-6ea9-4ccc-8a2c-43e2a69dae7a.png)

![image](https://user-images.githubusercontent.com/99641908/200811401-44f70860-a32a-4022-8759-e50728ee63e0.png)

![image](https://user-images.githubusercontent.com/99641908/200811607-a0d79606-bfce-4222-9504-39fcbf3c1f14.png)

![image](https://user-images.githubusercontent.com/99641908/200811732-d218db8c-c854-4d75-a541-05bbfe89dfca.png)

![image](https://user-images.githubusercontent.com/99641908/200812064-7be4190b-c29f-4cc5-91ce-d91164a6b70c.png)

`settings.json`:

```
{
    "Version": 1,
    "DynamicTree": {
        "AzOps": {
            "Core.AutoGeneratedTemplateFolderPath": ".",
            "Core.AutoInitialize": true,
            "Core.DefaultDeploymentRegion": "westeurope",
            "Core.EnrollmentAccountPrincipalName": "",
            "Core.ExcludedSubOffer": [
                "AzurePass_2014-09-01",
                "FreeTrial_2014-09-01",
                "AAD_2015-09-01"
            ],
            "Core.ExcludedSubState": [
                "Disabled",
                "Deleted",
                "Warned",
                "Expired"
            ],
            "Core.ExportRawTemplate": false,
            "Core.IgnoreContextCheck": false,
            "Core.IncludeResourcesInResourceGroup": ["*"],
            "Core.IncludeResourceType": ["*"],
            "Core.InvalidateCache": true,
            "Core.OfferType": "MS-AZR-0017P",
            "Core.PartialMgDiscoveryRoot": [],
            "Core.SkipPim": true,
            "Core.SkipPolicy": false,
            "Core.SkipResource": false,
            "Core.SkipChildResource": false,
            "Core.SkipResourceGroup": false,
            "Core.SkipResourceType": [
                "microsoft.alertsmanagement/smartDetectorAlertRules",
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "microsoft.visualstudio/account",
                "Microsoft.VSOnline/plans",
                "Microsoft.Insights/scheduledQueryRules"
            ],
            "Core.SkipRole": false,
            "Core.SubscriptionsToIncludeResourceGroups": ["*"],
            "Core.TemplateParameterFileSuffix": ".json",
            "Core.ThrottleLimit": 10,
            "Core.WhatifExcludedChangeTypes":[
                "NoChange",
                "Ignore"
            ]
        },
        "|AzureDevOps": {
            "!Condition": "EnvAzDevPipeline -or -not OSWindows",
            "AzOps.Core.State": "%PIPELINE_WORKSPACE%/s/root"
        },
        "|GitHub": {
            "!Condition": "EnvGithubAction",
            "AzOps.Core.State": "%GITHUB_WORKSPACE%/root"
        },
        "PSFramework": {
            "Message.Info.Maximum": 3
        }
    }
}
```

**Comment by daltondhcp** [comment]
> 

Thanks for sharing @bengeset96. The last two (related to child resources), looks like a downstream issue with the Export ARM API (internal server error) 
For the others, it would be great to get some more context on what specific resources/resource groups that are failing (i.e. the lines before the terminating errors appears) 

To simplify debugging, if possible, please send over some example pipeline logs over email to me on jodahlbo[at]microsoft.com.

**Comment by bengeset96** [comment]
@daltondhcp 

I've sent you some logs from the various runs on your email.

**Comment by jsandquist** [comment]
@BoostSebastian @bengeset96 I recognize a few of these, see #656, but after we reset the logging level to default 3 (instead of 9) and also changed the throttle limit to 1 instead of default 10 (although unsure if related at all) we no longer see this on a daily basis, but only once every week or so.

**Comment by bengeset96** [comment]
@jsandquist 

I've tried to throttle it down as well, but did not have any impact on the AzOps installations. I'll continue debugging and trying different scenarios. The larger the environment it is, the more often I do get it.

**Comment by daltondhcp** [comment]
Update: In 1.9.1, we introduced error handling to handle the "Internal Server Error" issues thrown from the ExportResources API. Please let us know if you observe improvements in the situation.

**Comment by BoostSebastian** [comment]
@daltondhcp I tried today to reimplement everything from scratch but exactly the same error.

```
Test-Path: Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

##[error]PowerShell exited with code '1'.
Finishing: Initialize
```

This happends right after our resource group with Exchange 2019 servers pool
This is maybe 4/10 and the rest at what I can only assume is random

**Comment by daltondhcp** [comment]
> @daltondhcp I tried today to reimplement everything from scratch but exactly the same error.
> 
> ```
> Test-Path: Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')
> 
> ##[error]PowerShell exited with code '1'.
> Finishing: Initialize
> ```
> 
> This happends right after our resource group with Exchange 2019 servers pool This is maybe 4/10 and the rest at what I can only assume is random

This looks like a completely different error, right?

**Comment by BoostSebastian** [comment]
@daltondhcp I don't know, getting different errors each time I run the Pipeline and at different lines. 
Here is four runs in a row.

![Greenshot 2022-12-01 15 44 39](https://user-images.githubusercontent.com/24891371/205082182-58753518-c91a-40a8-b34a-ea3967834032.png)

![Greenshot 2022-12-01 16 16 28](https://user-images.githubusercontent.com/24891371/205089858-595a9ffd-1044-4432-a151-f378ce1816ea.png)

![Greenshot 2022-12-01 16 49 52](https://user-images.githubusercontent.com/24891371/205097990-af872796-279d-42b2-8000-aba74e1a740c.png)


![Greenshot 2022-12-02 06 57 43](https://user-images.githubusercontent.com/24891371/205225276-8759b4b0-743c-44e3-8466-952e4fefb94a.png)

**Comment by BenjaminEngeset** [comment]
We're having the same issues as I can tell @BoostSebastian. I have spent quite much time troubleshooting, but still not any closer.

Johan has been kind and I have sent some logs, but they did not tell much.

Starting from scratch with blank repository state and different agent has not helped.

**Comment by BoostSebastian** [comment]
@BenjaminEngeset, I tried a blank repo but no success. I could back it up to 1.7 but same error again when changing to include resources and child-resources.

This seems to be the most commin error message:

`Write-PSFMessage: The term 'Write-PSFMessage' is not recognized as a name of a cmdlet, function`

**Comment by BoostSebastian** [comment]
I have tried to run many times now. 
One success and rest of the runs is failed on `Initialize` step.
At 1.9.1 it now always show.

`Write-PSFMessage: The term 'Write-PSFMessage' is not recognized as a name of a cmdlet, function`

![fails](https://user-images.githubusercontent.com/24891371/207606004-49c0775f-e1c1-44ca-9438-aa7ffddf19b6.png)

**Comment by BoostSebastian** [comment]
Any Updates :) Still the same Issues.

**Comment by daltondhcp** [comment]
Hey @BoostSebastian - sorry for the slow updates. We are aiming to ship AzOps 2.0 very soon that will introduce lots of performance improvements and also from what we've seen address the above. Keep your eyes peeled.

**Comment by BoostSebastian** [comment]
@daltondhcp Souund awesome :) I will try as soon it is released.
