### ISSUE TITLE
Public Ip; zones are removed on AzOpsPull command

### ISSUE THREAD

**Issue by woutermation** [Azure/AzOps#701]
**Describe the bug**

During an AzOpsPull cmd the Public IP settings for Zones are removed.

```powershell title="whatif result"
  ~ Microsoft.Network/publicIPAddresses/zone-1-pip [2022-07-01]
    - zones: [
        0: "1"
      ]
```

Push will then fail with the following ARM error as the Zone settings are no long present in the json:
  
```powershell title="push error"
New-AzResourceGroupDeployment: 13:48:12 - The deployment
'AzOps-microsoft.network_publicipaddresses-zone-1-pip-16FA' failed with
error(s). Showing 1 out of 1 error(s). Status Message: Resource
/subscriptions/XXXXXX/resourceGroups/zdk-we-p-rg-a
dds-2/providers/Microsoft.Network/publicIPAddresses/zone-1-pip has an existing
availability zone constraint 1 and the request has availability zone constraint
NoZone, which do not match. Zones cannot be added/updated/removed once the
resource is created. The resource cannot be updated from regional to zonal or
vice-versa. (Code: ResourceAvailabilityZonesCannotBeModified)   CorrelationId:
XXXXXXX
```

When re-adding the zone settings to the json a validate and push are working correctly, actions taken:
  
1. Create new branch
2. Re-apply zone settings in the pip json
3. Create PR
4. Validate will run successful
5. Merge
6. Push will run successful
  
**Steps to reproduce**

1. Create a public ip or use an existing
2. Start AzOpsPull  
  
**Screenshots**

![image](https://user-images.githubusercontent.com/13215912/201096494-c2981f05-34bf-4878-b225-61901ea9b1d7.png)

**Comment by daltondhcp** [comment]
Thank you for raising this! 
This unfortunately a known limitation of the resources API we take a dependency on to export the resources. 
We are looking for ways to solve this (and also improve overall pull performance), but currently no workarounds other than deploying these resources with custom templates.

**Comment by buys-stash** [comment]
@daltondhcp, Thanks for answering this issue. Good to know, we will keep this in mind untill a solution is found.
