### ISSUE TITLE
Invalid characters in Azure Alerts naming

### ISSUE THREAD

**Issue by buys-stash** [Azure/AzOps#709]
**Describe the bug**
  
ConvertTo-AzOpsState: 
Line |
  94 |  …  & $azOps { ConvertTo-AzOpsState -Resource $resource -ExportRawTempla …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified AzOpsState file contains invalid characters (remove any "[" or "]" characters)! Skipping /runner/_work/.../AzOps/root/tenant root group (xxx-xxxxx-xxxxxxx-xxxxxxx[80](https://github.com/organisation/repo/actions/runs/1234/jobs/1234#step:13:81)1234)/xx - connectivity (xxxx-xxxxx-xxxxx-xxx-xxxxx)/microsoft-network-westeurope/.state/microsoft.insights_metricalerts-[xx] - xxx0501-001-availability fired for config1234 in sub xx - connectivity and rg microsoft-network-westeurope.json
  
**Steps to reproduce**
  
1. Create an Azure Alert with the name containing a special character like []  
2. Try to Pull with AzOps  
3. It will fail cause of special character  
  
**Screenshots**
  
![image](https://user-images.githubusercontent.com/59330302/203082754-2181c703-bf9e-4f12-9227-bc99b8c027ba.png)

**Comment by daltondhcp** [comment]
Thank you for raising this? 
This is currently by design and described in the FAQ @https://github.com/azure/azops/wiki/frequently-asked-questions#subscriptions-or-resources-not-showing-up-in-repository. Are you manually adding these brackets to the metricalert-names, or is it done by Azure Monitor?

**Comment by buys-stash** [comment]
> Thank you for raising this? This is currently by design and described in the FAQ @https://github.com/azure/azops/wiki/frequently-asked-questions#subscriptions-or-resources-not-showing-up-in-repository. Are you manually adding these brackets to the metricalert-names, or is it done by Azure Monitor?

Currently we add them as part of our naming convention for Azure Alerting. If this is not compatible with AzOps we can adjust the current naming convention off course.

**Comment by daltondhcp** [comment]
As it has some ripple effects across various parts of the code base, it is currently not supported. 
See #351,  #443 and #456 for further details.
