### ISSUE TITLE
Validate pipeline sets wrong "headline" in comments.

### ISSUE THREAD

**Issue by bjompen** [Azure/AzOps#716]
**Describe the bug**

When the validate pipeline posts comments it sets the filename for the resource group as headline.
This may be confusing as it shows the name of a template not actually deployed.

Given a folder containing a template for resource group, `microsoft.resources_resourcegroups-alz-lz1.json`, and adding or changing other templates in the same folder, `SANumber1.bicep`, the feedback still says it comes from the resource group template.

To avoid confusion it should instead show for example the scope as seen right above the actual resources.

**Steps to reproduce**

1. Create a template for a resource group
2. Create a template for another resource
3. run validate pipeline

**Screenshots**

![image](https://user-images.githubusercontent.com/17783007/204299341-ce0fb69c-5d2e-4c36-ac4c-408b393028c6.png)

**Comment by daltondhcp** [comment]
Thank you for raising this. We will fix it in an upcoming release.
