### ISSUE TITLE
Undesired warning in pipeline output for parameter files during deployment/validate

### ISSUE THREAD

**Issue by bjompen** [Azure/AzOps#717]
**Describe the bug**

Related to #504 (?)

When deploying a template alongside a parameter.json file the Azure DevOps log outputs a warning for the parameter.json.

```
WARNING: [13:37:00][AzOpsScope] Unable to determine type from Template or Template Parameter file: /home/vsts/work/1/s/root/root <...>/templateName.parameters.json
```

As this parameter file isn't even supposed to be deployed this warning clutters the output and gives bad feedback.

**Suggestions**

Either make this an opt in and only show this message when high verbosity or similar is set,
_or_
Change this to a informational message
_or_
Do not parse/include .parameters.json files at all in the list of files to process as they most likely aren't _ment_ to be deployed..

**Steps to reproduce**

1. Deploy a resource.bicep with a resource.parameters.json
2. check the Azure DevOps output

**Screenshots**

![image](https://user-images.githubusercontent.com/17783007/204310035-557c7fef-082e-4f7e-aeca-e5fd497a17a1.png)

**Comment by jsandquist** [comment]
Regarding alternative 3 there is a scenario where only the params file is present in git. Forgot the details but will add later.

Somewhat related... if you deploy a resource group using an ARM template with a params file the params file is deleted by the next pull and the subsequent push will fail validation.

**Comment by daltondhcp** [comment]
Thank you for raising this. As Jan pointed out, this is currently by design as per discussion in #677. We will consider changing this in the future.
