### ISSUE TITLE
customSorting does not support files without a parent folder

### ISSUE THREAD

**Issue by egullbrandsson** [Azure/AzOps#721]
**Describe the bug**
This is a bug in the AzOps-Accelerator repo.
The script customSorting.ps1 does not support files without a parent folder e.g., settings.json

**Steps to reproduce**

1. Edit settings.json
2. Push to main

**Screenshots**
Added additional write-host to show output.
![image](https://user-images.githubusercontent.com/55599263/205056048-74e85952-0456-49a6-9dc7-be50cc88cc10.png)

PR that solves this issue:
[AzOps-Accelerator/pull/131](https://github.com/Azure/AzOps-Accelerator/pull/131)

**Comment by daltondhcp** [comment]
Thank you for raising this. However, I fail to understand the scenario where you would want to act on things in settings.json?
