### ISSUE TITLE
Gitcommand Bug Report

### ISSUE THREAD

**Issue by ramuvr** [Azure/AzOps#732]
Github Command to set can_approve_pull_request_reviews should have upper case -F instead of -f 

**Steps to reproduce**

Running 

gh api -X PUT /repos/{owner}/{repo}/actions/permissions/workflow -f can_approve_pull_request_reviews=true

produces 

{
  "message": "Invalid request.\n\nInvalid property /can_approve_pull_request_reviews: `\"true\"` is not of type `boolean`.",
  "documentation_url": "https://docs.github.com/rest/reference/actions#set-default-workflow-permissions-for-a-repository"   
}
gh: Invalid request.

Changes to -F can_approve_pull_request_reviews=true works fine as per documentation URL supplied in earlier error.

**Screenshots**

**Comment by ramuvr** [comment]
<img width="988" alt="Untitled" src="https://user-images.githubusercontent.com/27629864/208807790-6c31dec8-ec73-429e-bf86-d2a7ec828c86.png">

**Comment by daltondhcp** [comment]
Thank you for raising! Do you want to contribute with a PR to the documentation

**Comment by ramuvr** [comment]
> Thank you for raising! Do you want to contribute with a PR to the documentation

I don't have permission to push, do I need to create a fork and push?

**Comment by daltondhcp** [comment]
> > Thank you for raising! Do you want to contribute with a PR to the documentation
> 
> I don't have permission to push/create branch on the repo, do I need to create a fork and push?

Exactly - just as in any OSS repo on GitHub

**Comment by ramuvr** [comment]
Thanks I think I have created it correctly, please see PR #734
