### ISSUE TITLE
Pull pipeline removing the metadata from policy exemptions and assignment file

### ISSUE THREAD

**Issue by nishantmittal6239** [Azure/AzOps#742]
**Describe the bug**
We need to have the metadata in the exemptions and assignment file like we have in policy definition and policy set definition. According to the Microsoft documentation we can have the metadata in the policy assignment as well. But when we push the assignment with the metadata and when the next pull happen, It removes the metadata from the file. See screenshot.

**Steps to reproduce**

1.
![az-ops_error_2](https://user-images.githubusercontent.com/105919737/216989497-77e575e3-eeae-4cba-87e0-bc52c4823490.PNG)

2.

**Screenshots**

**Comment by daltondhcp** [comment]
Thanks for the input @nishantmittal6239, we will ship an update that solved for this in the next release
