### ISSUE TITLE
Error Configuring AzOps using Azure CLI in PowerShell

### ISSUE THREAD

**Issue by daltondhcp** [Azure/AzOps#753]
### Discussed in https://github.com/Azure/AzOps/discussions/750

<div type='discussions-op-text'>

<sup>Originally posted by **petropmi** February 17, 2023</sup>
Hi everyone,

I'm facing an error each time I'm executing the PowerShell script that configures the Azure DevOps project. Although the project, repo, and the pipelines are created successfully, later on, fails at the step of assigning permissions to the Build Service account.

The error is the following:

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No connection adapters were found for '"https://vssps.dev.azure.com/organization/_apis/identities?searchFilter=General&queryMembership=None&api-version=6.0&filtervalue=azops-artofcloud Build Service (organization)"'.

Any ideas are welcomed! </div>

**Comment by daltondhcp** [comment]
@SimonWahlin - seems like this came back today - do you mind taking a look?

**Comment by SimonWahlin** [comment]
I'll try to reproduce it and see if I can find a solution

**Comment by SimonWahlin** [comment]
The problem is that az cli no longer accepts escaped json strings as input. Removing the escapes should solve the problem.

I'll try to make some time to update the wiki.

**Comment by daltondhcp** [comment]
@SimonWahlin - any updates on this?
