### ISSUE TITLE
Feature Request - Validate - parameter to indicate temp folder for WhatIf output

### ISSUE THREAD

**Issue by jsandquist** [Azure/AzOps#754]
As a follow-up to #678 and the related fix in #679 to generalize temp pathing - I recently had to support a scenario that involved running the AzOps pipelines on a self-hosted Windows VM.

I have a working setup but thought I'd share some observations anyway:

1. In case of multiple pipeline agents on the same machine ensure you lock the Validate (and Push) pipeline to one of the agents (e.g. using `demands` with Azure Pipelines)
2. Upon pipeline startup - remove any previous `OUTPUT.md / OUTPUT.json` files left from past runs
3. Update the pipeline code as follows:

```
# Expected path to WhatIf output to match the AzOps internals
$whatIfOutputPath = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "OUTPUT.md"
```

Preferably, I would like to indicate something like `Agent.TempDirectory` (if using Azure Pipelines) as an argument to the `Invoke-AzOpsPush` call.

I realise this is an edge case as opposed to running the pipeline on a short-lived temporary agent. Alternatively, this might go into the wiki if at all.

**Comment by daltondhcp** [comment]
Thank you for raising this. I do agree it is an edge case when not using short-lived agents/runners.
Perhaps a note or two in this https://github.com/azure/azops/wiki/self-hosted would be enough as a starting point? What do you think?
