### ISSUE TITLE
Invalid character error

### ISSUE THREAD

**Issue by danielesasia** [Azure/AzOps#755]
Hi all,
when perfoming Pull on our entire Azure structure, we recieve this error and pull fails

WARNING: [10:39:20][ConvertTo-AzOpsState] The specified AzOpsState file contains invalid characters (remove any "[" or "]" characters)! Skipping

This is happening on a single resource containing "brackets" in its name ("start-stop-vm[la-sap-vm-scheduler].json")

I have seen this FAQ @https://github.com/azure/azops/wiki/frequently-asked-questions#subscriptions-or-resources-not-showing-up-in-repository ;
Anyway there are resources created by microsoft that contains square brackets by default.
So far the only solution I found is to skip all the objects having the same type of the one causing the problem, but its quite a weird solution. Is there any way at least to simply skip one reource based on his name/ID?

Thank you all in advance.
D

**Comment by daltondhcp** [comment]
Thank you for raising this, this is currently by design. We are aware of the fact that some Microsoft-created resources use these characters.
We will discuss internally how to improve this and update as soon as possible.

**Comment by danielesasia** [comment]
Thank you @daltondhcp for your quick answer. I really hope to find this new feature soon available.
