### ISSUE TITLE
Errors on initialize step with latest module version (2.0.1)

### ISSUE THREAD

**Issue by gregslack78** [Azure/AzOps#757]
Since the latest module was installed I am seeing a number of errors in the pull initialize step immediately after "Processing Management Group [Tenant Root Group]"

Where-Object: The term 'Where-Object' is not recognized as a name of a cmdlet, function,
script file, or executable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
##[error]PowerShell exited with code '1'.

SetValueInvocationException: Exception setting "type": "The property 'type' cannot be found on this object.
Verify that the property exists and can be set."
##[error]PowerShell exited with code '1'.

Write-PSFMessage: The term 'Write-PSFMessage' is not recognized as a name of a cmdlet, function,
script file, or executable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
##[error]PowerShell exited with code '1'.

**Steps to reproduce**

1.  Run a pull pipeline ensuring you are on the latest module version (2.0.1)

**Screenshots**
![image](https://user-images.githubusercontent.com/85254974/220418407-cbb03909-7f12-49e0-9a69-fe0fc40b8659.png)

**Comment by daltondhcp** [comment]
Thank you for reporting. We have seen this issue intermittently even prior to 2.0.0. Can you confirm if it worked on second attempt or if it breaks on every run?

**Comment by gregslack78** [comment]
Run 1 was

Write-PSFMessage: The term 'Write-PSFMessage' is not recognized as a name of a cmdlet, function,
script file, or executable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
##[error]PowerShell exited with code '1'.


Run 2 was..

SetValueInvocationException: Exception setting "type": "The property 'type' cannot be found on this object.
Verify that the property exists and can be set."
##[error]PowerShell exited with code '1'.

Run 3, 4,5 have been...

Where-Object: The term 'Where-Object' is not recognized as a name of a cmdlet, function,
script file, or executable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
##[error]PowerShell exited with code '1'.



________________________________

**Comment by daltondhcp** [comment]
Thanks. Can you change ‘"Message.Info.Maximum"‘ to 9 (debug) to hopefully get additional insights what it is failing on.

**Comment by jsandquist** [comment]
@gregslack78 FYI - some references to previous findings: #656 and #699.

**Comment by daltondhcp** [comment]
Thanks for the input, @jsandquist. I've had some side conversations with Greg and it indeed seems to be related to the increased parallelization in 2.0. 

While we are nailing down the exact pattern and how to sustainably mitigate this from a more holistic point of view, I have advised to lower the `"Core.ThrottleLimit"` from default 10 to 5 or lower, which seems to have mitigated the issue during our attempts to reproduce the problem.

**Comment by gregslack78** [comment]
To keep this up to date, GM went with rolling back the module version to 1.9.4.
________________________________
