### ISSUE TITLE
Regression (?) - Core.SubscriptionsToIncludeResourceGroups filter (2.0.1)

### ISSUE THREAD

**Issue by jsandquist** [Azure/AzOps#758]
**Describe the bug**

I experienced some unexpected behaviour with v2.0.1 - related to

Core.SubscriptionsToIncludeResourceGroups

I was a bit surprised that with the same settings.json used with 1.9.4 I got some additional resource groups in the first big Pull Request.

No matter what filter I've tried it behaves like '*' and includes resource groups for all subscriptions.

It properly excludes the resources themselves though according to my settings.json.

**Steps to reproduce**

1. TBD
2.

**Screenshots**

**Comment by daltondhcp** [comment]
Thanks for reporting @jsandquist. 

I just validated this in my own environment and it seems to work as "expected". 
However, it seems like we introduced a breaking change to only allow filter based on subscriptionId, and not displayName as before. 

Below is what I used successfully in my environment:

```
"Core.SubscriptionsToIncludeResourceGroups": ["c62c2473-9d97-4014-a42c-dd41f1b3c5e7",
                                              "6307c1fd-dbda-4b32-bd62-b97a5a146bb1",
                                              "afffa704-8cbd-46f2-a146-b473f632ecb5"
                                             ],
```

Please let us know if this works for you as well.

**Comment by jsandquist** [comment]
Thanks for the quick response! 😃

My scenarios can be explained something like this:

I used this setting to filter out resource groups in sandbox subscriptions (based on display name) but still keep any subscriptipn specific policies in git state.

In combination with the resource group filter (haven't verified it yet) we can then keep track of centrally managed resources in all lz subscriptions.

I'll investigate some more on my side.

**Comment by jsandquist** [comment]
Ah, sorry for the noise - I apparently did not pay enough attention to the breaking change described in the 2.0 release notes.

**Comment by daltondhcp** [comment]
> Ah, sorry for the noise - I apparently did not pay enough attention to the breaking change described in the 2.0 release notes. Closing 😃

No worries. It happens to the best of us :)
