### ISSUE TITLE
Feature Request - bicep build should throw exception if transpilation failed 

### ISSUE THREAD

**Issue by borondy** [Azure/AzOps#767]
**Failing bicep builds are swallowed in validate/push pipelines**

We experienced recently that our invalid bicep files were not causing failed validate/push pipeline executions. 
We'd prefer to see both pipelines to fail if the bicep changes are invalid. Currently the logs in our pipelines are printing out the errors coming from the bicep build command, but these errors are not causing any further issue up on the chain. 
ConvertFrom-AzOpsBicepTemplate returns with the expected transpiledTemplatePath even if the transpilation failed. This path is used later in the deployment commands, and as we see it now, they are only creating a Path not found warning, so the errors with the bicep files were simply swallowed. 

**Suggestion:**
Throw exception if the bicep build command fails to produce arm/json output file.

**Comment by Jefajers** [comment]
Thanks for reporting this @borondy and associating a PR to address the behavior 😀.
