### ISSUE TITLE
Push Action fails when Debug and Verbose are set to "1" 

### ISSUE THREAD

**Issue by dzemp** [Azure/AzOps#77]
**Describe the bug**
Debug and Verbose are both set to "1" in azops.yml. AzOps Push Action now fails with the following error message returned:

Confirm
Are you sure you want to perform this action?
Performing the operation "Start-AzOpsNativeExecution" on target "Update 
ErrorActionPreference to Continue?".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help 
Write-AzOpsLog: /action/entrypoint.ps1:53
Line |
  53 |              Write-AzOpsLog -Level Error -Topic "entrypoint" -Message  …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [2020-07-14 08:55:50.2249] (entrypoint) Exception calling
     | "ShouldProcess" with "1" argument(s): "Object reference not
     | set to an instance of an object."

(default is "Y"):

**Steps to reproduce**

1. Set Debug and Verbose in azops.yml to "1"
2. Create PR that invokes Push Action

**Screenshots**

**Comment by ljtill** [comment]
Thanks for reporting this @dzemp, I'll investigate this bug and update this thread shortly.

**Comment by ljtill** [comment]
Fix has been merged into the main branch and also added to the release/v0.3 branch.
