### ISSUE TITLE
Firewall Policy Rule Collections are not getting templated

### ISSUE THREAD

**Issue by scotthainesjr** [Azure/AzOps#777]
**Describe the bug**
There is no way for me to see the Firewall Policy Rule Collections. The Template produced for the Firewall Policy is basic and does not include this, and the Rule Collections are also not being populated as their own independent child resource. I have child resources set to true in settings. 

**Steps to reproduce**

1.
2.

**Screenshots**
This is a screenshot of the generated template
![image](https://user-images.githubusercontent.com/11492630/225377269-4693ac3d-c1fd-4abb-a29f-106a00708871.png)

Here is a template from the portal, showing the rule collections
![image](https://user-images.githubusercontent.com/11492630/225377502-e058c18b-f598-4f2c-9172-7e1440c6d7ed.png)

**Comment by daltondhcp** [comment]
Can you share your full settings.json please.

**Comment by scotthainesjr** [comment]
My last run seems to have populated them, not sure if I just missed them, or if they were generated in the latest run. Closing bug
