### ISSUE TITLE
GitHub repo creation from AzOps failing for Enterprise Managed User.

### ISSUE THREAD

**Issue by jimman100** [Azure/AzOps#784]
I am trying to deploy Azure landing zone portal accelerator. I have created the GitHub PAT and provided the token and the org name in the CI/CD set-up step. But the deployment is failing with the AzOps GitHub set-up step, 

New-GitHubRepositoryFromTemplate -AccessToken XXXX -OwnerName Azure -RepositoryName AzOps-Accelerator -TargetRepositoryName XXX -TargetOwnerName XXXX -Private
 
is failing with the below error

Line |
 313 |              $result = Invoke-WebRequest @params
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"Unauthorized: As an Enterprise Managed User, you cannot access this
     | content","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-using-a-template"} 

I am able to create a repo fine using the same PAT from GitHub CLI.

Can you please let me know if there is any limitation with the enterprise managed users ?  Please note, I have authenticated the PAT to use SSO also.

Thanks
JP

**Comment by daltondhcp** [comment]
Hi,

This is a known limitation with GitHub Enterprise Managed Users. See https://github.com/Azure/AzOps/issues/576 for more details. 

Thanks,
Johan
