### ISSUE TITLE
Drift Detection in AzOps

### ISSUE THREAD

**Issue by PoborcaMaciej** [Azure/AzOps#788]
Hello, 

Maybe i am just blind, but I cannot find option to detect drifts (Change in the portal, lack of the change in the code). I know that tool is working bidirectional, but I think that some of the companies would like to detect drifts firstly, not using pull pipeline by default. 

Is it something that exists already, or maybe you are thinking to introduce such functionality ?

**Comment by daltondhcp** [comment]
AzOps can be a useful tool for detecting drift in your Azure platform using the Pull pipeline. To make the most of this, it's important to deploy your resources using AzOps Push pipeline, which ensure that the desired state is always stored in the repository. 

This way, any changes made outside of the proper toolset will show up as out-of-band changes in the automated pull requests generated by the Pull pipeline. 
By adding approvals before merging these pull requests, you can take action on any detected drift and keep your infrastructure in a consistent state.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/16622613/233335715-9e150cb3-8ae3-4607-ab18-755b8daeac90.png">

If you have suggestions on how to enhance this, we are open for feedback! 👍🏻

**Comment by daltondhcp** [comment]
Hey @PoborcaMaciej - did the above make any sense or do you have additional feedback on how we can improve/enhance this?

**Comment by daltondhcp** [comment]
Closing issue for now. Feel free to reopen if you have any feedback on how we potentially could/should improve this.
