### ISSUE TITLE
Multiple subscription creation

### ISSUE THREAD

**Issue by jimman100** [Azure/AzOps#796]
Hi,
How do  I create multiple landing zones under one management group using a single ARM template file ? . I tried to use the emptySubscription.json and emptySubscription.parameters.json file but looks like i need t have a new .json and .paramters.json file for each subscription that i am creating. Is there a way to use just a single file for the subscription and use multiple values in the subscription file ? Say today, I have a request for one subscription which i will add the values in paramters.json file and tomorrow when i have a request to create another subscription, i would like to just append the values in the .parameters.json file and create the PR so that AzOps can deploy the new subscription ? is this doable or do i need to have a subscription and parameters file for each new subscription that i want to provision ? 

Thanks
Jimmy

**Comment by daltondhcp** [comment]
Hi Jimmy,

Let's continue the conversation in the already started discussion. https://github.com/Azure/AzOps/discussions/793
