### ISSUE TITLE
Creating subscription by adding just the paramter file 

### ISSUE THREAD

**Issue by jimman100** [Azure/AzOps#803]
Hi,
 I will have one newSubscription.json file which is already in the repo, when i want to create a new subscription, i will create a new parameter file and merge it. please note, i will only check-in the parameter file, can the workflow, create the subscription based on just the parameter file or do i need to check-in the template file also along with the parameter file each time (2 files per PR) to create the subscription ?

say newSubscription.json is already in the repo, i will then create newSubscription.1.paramters.json and create a PR with justnewSubscription.1.paramters.json and when i merge the PR, can it create the subscription. I tried this and the validate workflow had failed.

Does it need to be always 2 files per PR for the subscription to be created ?
Please see the error I am getting in the attached file, when i am trying to create a new parameter file per subscription.
<img width="781" alt="validateerror" src="https://github.com/Azure/AzOps/assets/125463962/0681184c-beb9-4b76-aa31-0849e71ed94d">

**Comment by daltondhcp** [comment]
Currently, we have a 1:1 dependency between parameter file and template to make it deterministic. So the current approach (as discussed in https://github.com/Azure/AzOps/discussions/793), would be to add logic in the template to handle multiple subscriptions and update newsubscription.parameters.json with the additional subscription.

**Comment by daltondhcp** [comment]
Any updates here, @jimman100?

**Comment by jimman100** [comment]
My apologies, we decided to go with the approach of creating a template file and parameters file for each subscription. You may please close this issue
