### ISSUE TITLE
Feature Request - Azure DevOps ARM Service Connections with AzurePowerShell tasks

### ISSUE THREAD

**Issue by Agger1995** [Azure/AzOps#806]
Hi.

In our organization we have recently adopted AzOps to accelerate our adoption of an Enterprise Scale Azure landing zone architecture.
We have done so using the [AzOps Accelerator](https://github.com/Azure/AzOps-Accelerator) template repository, and the general scripts provided on the Wiki for getting started with AzOps.
We work primarily with Azure DevOps, and are also using the starter ADO pipeline templates for Pull, Push & Validate.
The starter templates assumes certain variable groups exists, one with credentials for a service principal, another with AzOps configuration.

In our setup, the AzOps service principal is a highly priviledged user, and should therefore be treated as such. We didn't feel like variable groups were a correct fit for storing credentials for this highly priviledged service principal.

As such, instead of referring the variable group, we would like to be able to use an ADO ARM service connection with the service principal, for authenticating with Azure, and utilize the [`AzurePowerShell@5`](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) task in the AzOps Pull/Push/Validate pipelines in Azure DevOps.

This ensures that the credentials in the variable group can't be abused.

We have a working code example of a pipeline which solely uses the ADO ARM service connections and the `AzurePowerShell@5` task, which I will share with you below as inspiration.

The pipeline assumes an ARM service connection exists with the name `arm-service-connection`. In our example setup we have configured the service connection to be scoped to a management group, but it should work similarly with subscription scoped.
I would like to stress that I have only been successful in getting this to work with version 10.0.0 of Azure PowerShell.

```yaml
name: "Test"

trigger: none

variables:
  - template: .templates/vars.yml

jobs:
  - job: test
    displayName: "AzOps Pull - ADO ARM - Test"
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - task: AzurePowerShell@5
        displayName: "Initialize"
        inputs:
          azureSubscription: "arm-service-connection"
          scriptType: "InlineScript"
          preferredAzurePowerShellVersion: 10.0.0
          Inline: |
            $latestVersionId = Find-Module -Name AzOps | Select-Object -ExpandProperty Version
            Write-Host "##vso[task.setvariable variable=AZOPS_MODULE_VERSION;]$latestVersionId"

            if(-not (Test-Path -Path '$(modulesFolder)')) {
              mkdir '$(modulesFolder)'
            }
            $params = @{
              Name            = 'AzOps'
              Path            = '$(modulesFolder)'
              Force           = $true
            }
            if('$(AZOPS_MODULE_VERSION)') {
              $params.RequiredVersion = '$(AZOPS_MODULE_VERSION)'
            }
            Save-Module @params

            $Env:PSModulePath = $Env:PSModulePath, '$(modulesFolder)' -join [IO.Path]::PathSeparator
            Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
            Invoke-AzOpsPull -Rebuild
            Get-Job | Remove-Job -Force
```

**Comment by daltondhcp** [comment]
Thanks for the great suggestion! We will likely not update the default guidance/accelerator for now to use service connections.
However, we are looking to overhaul the ADO guidance with respect to SPs once https://learn.microsoft.com/en-us/azure/devops/release-notes/roadmap/2022/secret-free-deployments to avoid dealing with secrets overall when not using managed identities.

**Comment by Agger1995** [comment]
Cool!
That would be an even greater solution over all, and would also solve our current main concern. 
I look forward to seeing that implemented.
Thanks for bringing that to my attention.

Seeing as you won't be implementing support for ADO service connections, we can close this issue. 
I will leave the pipeline example for others who may want to modify the ADO starter templates to use service connections.
Thanks for your time!
