### ISSUE TITLE
Validate Pipeline Results Step - Invoke-RestMethod Failure

### ISSUE THREAD

**Issue by nishantmittal6239** [Azure/AzOps#807]
Describe the bug:
We are getting issues on Validation pipeline. Could you please check the attached screenshot and solve it ASAP?

**Steps to reproduce**

1. Just trigger a PR and validation pipeline is failing.
2.

**Screenshots**
![image](https://github.com/Azure/AzOps/assets/105919737/3045efce-ba33-4ba9-9afe-3344d7a8ae20)

**Comment by Jefajers** [comment]
Hi @nishantmittal6239, we are not able to reproduce the issue that you have shared (please confirm if this is a transient issue.).

The default [AzOps-Accelerator](https://github.com/Azure/AzOps-Accelerator/blob/47b9d50d611a663d8c827e1928cfd3413b6553b6/.pipelines/validate.yml#L69) `Results` step in the pipeline referenced utilizes PowerShell `Invoke-RestMethod`. Unable to troubleshoot further without more information.

Please share pipeline step, module version and have a look if you have lingering `/tmp/OUTPUT.md`  content.

**Comment by daltondhcp** [comment]
Any input here, @nishantmittal6239?

**Comment by daltondhcp** [comment]
@nishantmittal6239 - any updates here or can the issue be closed?

**Comment by nishantmittal6239** [comment]
Hi Johan, You can close this ticket. I think it was auto-resolved.
