### ISSUE TITLE
Policy definition is overwritten by AzOps engine during the pull

### ISSUE THREAD

**Issue by nishantmittal6239** [Azure/AzOps#810]
Policy definition is overwritten by AzOps engine during the pull. Even the Azure still have the policy initially created by AzOps remove some part of the policy [definition.](url)

**Steps to reproduce**

1. Attaching the original policy def which is deployed on the cloud and still exists as it is.
2. Attaching the policy def which change by AzOps.

**Screenshots**
[originalpolicy.txt](https://github.com/Azure/AzOps/files/11849922/originalpolicy.txt)

[AzOpsUpdatedPolicy.txt](https://github.com/Azure/AzOps/files/11849923/AzOpsUpdatedPolicy.txt)

**Comment by Jefajers** [comment]
Hi @nishantmittal6239, thanks for raising this and sharing an example.

I am able to reproduce and am now considering ways to rectify this.
