### ISSUE TITLE
Custom sort order breaks when making changes to files in the root of the repository

### ISSUE THREAD

**Issue by Xitric** [Azure/AzOps#814]
**Describe the bug**

Imagine we add a file such as `bicepconfig.json` to the root of our AzOps repository when using the AzOps Accelerator. When enabling custom sort ordering, the directory resolved for any file in the root of the repository (such as `bicepconfig.json`) will be an empty string:

```powershell
Split-Path -Path 'bicepconfig.json' -Parent # <empty string>
```

When later joining this path to resolve potential `.order` files, the pipeline fails since `Join-Path` does not accept empty strings:

```powershell
$orderPath = Join-Path -Path $directoryPath -ChildPath '.order'
```

**Steps to reproduce**

1. Fork the AzOps accelerator repository.
1. Enable custom sort ordering by setting `AZOPS_CUSTOM_SORT_ORDER` to `true`.
1. Make a change to a file in the root of the repository, such as adding a `bicepconfig.json` or modifying an existing file.
1. Run the validation pipeline and observe how it fails at `$orderPath = Join-Path -Path $directoryPath -ChildPath '.order'`

**Screenshots**

_Not relevant._

**Potential solutions**

1. Use `[System.IO.Path]::Combine($directoryPath, '.order')` instead to resolve `.order` files, since this does support empty strings.
1. Don't attempt to resolve `.order` files if the directory is an empty string, since we are not deploying anything from this scope anyway (at least I think not).

**Comment by daltondhcp** [comment]
@SimonWahlin  - can you take a look at this one?

**Comment by SimonWahlin** [comment]
Absolutely!

**Comment by daltondhcp** [comment]
@Xitric - would you mind validating the change in https://github.com/Azure/AzOps-Accelerator/pull/137 before we merge?

Thanks in advance!

**Comment by Xitric** [comment]
@daltondhcp Of course, I'll get right at it!

**Comment by Xitric** [comment]
@SimonWahlin @daltondhcp The pipeline runs just fine now, LGTM
