### ISSUE TITLE
Always export Set-AzOpsWhatIfOutput results to json file

### ISSUE THREAD

**Issue by noopman** [Azure/AzOps#817]
The function [Set-AzOpsWhatIfOutput](https://github.com/Azure/AzOps/blob/main/src/internal/functions/Set-AzOpsWhatIfOutput.ps1) has logic for result size limit. It specified a parameter for modifying this size with a default of 64 000 characters. I am running into this issue a lot when deploying large initiatives and such to Azure. The calls to this internal function from this cmdlet library never specify this value, meaning I don't see how I can customize this value.

I propose an [AzOps Setting](https://github.com/azure/azops/wiki/settings) for this value, including the option to disengage limitation altogether! I would like to set someting like `Core.WhatifResultSizeMaxLimit` or `Core.WhatifResultNoMaxLimit`.

I don't see any reason for this limitation at all. Perhaps that can be explained here! If the result is already returned and the returned data already contains all this information, why truncate it outside of my control? Why not just return it to me, or at least allow me to choose what to do with it?

Another option would be that you return a reference to a file and allow me to turn it into a an artifact in my pipeline that I may upload and store.

**Comment by daltondhcp** [comment]
Thanks for the feedback, @noopman. 

The limitation stems from ADO/GitHub comment limitations. 
#417 
https://github.com/orgs/community/discussions/41331

We are contemplating posting larger WhatIf outputs by dividing them into N comments instead of not posting at all. Your thoughts?

**Comment by noopman** [comment]
While having the comments posted into the gh pr is "fine" and good if the length is smaller <64k, I think you should give me a file reference to the whole log and allow me to make it an action run artifact instead! I can open the whole thing, no matter how many characters, as I please!

Here's a thought: Always give me the file reference so I can make it into an artifact, as mentioned, AND take the first 64k characters and put into the comment as you are attempting to do today - but also CLEARLY state that there is more which did not fit here.

I think it would be worse to start adding many gh pr comments, because it will be difficult to read and the length of it all makes it less useful. If the output is so lengthy, then it is better to use it as an artifact!

Does that make sense?

**Comment by daltondhcp** [comment]
> While having the comments posted into the gh pr is "fine" and good if the length is smaller <64k, I think you should give me a file reference to the whole log and allow me to make it an action run artifact instead! I can open the whole thing, no matter how many characters, as I please!
> 
> Here's a thought: Always give me the file reference so I can make it into an artifact, as mentioned, AND take the first 64k characters and put into the comment as you are attempting to do today - but also CLEARLY state that there is more which did not fit here.
> 
> I think it would be worse to start adding many gh pr comments, because it will be difficult to read and the length of it all makes it less useful. If the output is so lengthy, then it is better to use it as an artifact!
> 
> Does that make sense?

See my updated comment, we actually do have a hardcoded file reference for the output :) 
![image](https://github.com/Azure/AzOps/assets/16622613/cca4d514-0f43-45e1-bb4c-7e4963f079f6)

**Comment by noopman** [comment]
That is excellent! I will try this out and let you know. I would propose you document how to turn that into an artefact! And I also propose you put as much as possible into on GH comment, but not multiple comments. I'd rather you reference the full file instead. I think multiple comments will look weird

**Comment by RSMagnusMartensson** [comment]
Sorry, that does not work. When the result is too long the file is NOT generated at all.

https://github.com/Azure/AzOps/blob/061d024b984f891d5d4266f55379ed0b27a49058/src/internal/functions/Set-AzOpsWhatIfOutput.ps1#L65

We'd need a code change to always generate the file content, regardless if it is too long for a GH comment!

**Comment by daltondhcp** [comment]
> Sorry, that does not work. When the result is too long the file is NOT generated at all.
> 
> https://github.com/Azure/AzOps/blob/061d024b984f891d5d4266f55379ed0b27a49058/src/internal/functions/Set-AzOpsWhatIfOutput.ps1#L65
> 
> I get the message here from the if-statement. You are referring to a code line in the else section.
> 
> We'd need a code change to always generate the file content, regardless if it is too long for a GH comment!

You are right, apparently I was too quick when scrolling through the references yesterday. We'll make sure to fix that in our next release.
