### ISSUE TITLE
Parallel Deployments Support

### ISSUE THREAD

**Issue by Jefajers** [Azure/AzOps#832]
## Deployment time

_This issue is a split from #831_ 

Today AzOps deploys templates from the change set sequentially.

Assuming a deployment for a customer with minimal changes takes 6 minutes, it only takes 10 customers for the deployment to reach 1 hour. Having instead performed 10 parallel deployments, we could be done in 6-7 minutes.

If we decide to add a Redis cache to every customer for a new application workload, each deployment could suddenly reach 30+ minutes. Now parallel deployments are more or less becoming a requirement.

We would prefer if the ability to perform parallel deployments is handled by AzOps. If instead we need to coordinate a series of individual pull requests, we are more or less back to imperative deployment pipelines, or we need to build a custom solution on top.

### Reducing the blast radius

With the approach outlined here, it is true that a change to the Bicep or ARM template would affect all deployments at the same time. If we wish to roll out the change in smaller intervals with monitoring in-between, or perhaps just at different frequencies, we have already considered dividing customers into stamps. Here is a simple example:

```
├── customer-stamp1.a.parameters.json
├── customer-stamp1.b.parameters.json
├── customer-stamp1.bicep
├── customer-stamp2.c.parameters.json
└── customer-stamp2.bicep
```

**Comment by Xitric** [comment]
@Jefajers I wonder how parallel deployments might actually be implemented in AzOps. Perhaps a configuration option to control the maximum degree of parallelism (defaulting to no parallelism), and then allow all deployments to be parallel unless they are mentioned in an `.order` file? Templates mentioned in an `.order` file should then probably be deployed first, in sequence as usual.

However, the `.order` file and associated logic is part of the accelerator, not AzOps itself.

**Comment by Jefajers** [comment]
Hi @Xitric, yes you are correct that custom sort order happens "independent of the AzOps module" and that the degree of parallel execution would need to accept configuration input and default to existing behavior of 1 deployment thread.

Targeting to formulate a plan during next week, will get back to you, atm working on bringing #831 to fruition.

**Comment by Xitric** [comment]
@Jefajers Awesome, thanks for working on this! We are really looking forward to the next release to try this out! 🚀
