### ISSUE TITLE
Folder names prefixed with "."

### ISSUE THREAD

**Issue by greyghostbrewery** [Azure/AzOps#837]
**Describe the bug**
Folder names in this repo are prefixed with a period (".").

This is generally used for hidden folders, and as such causes issues in applications such as File Explorer when "Show Hidden Files and Folders" is disabled.

Is there a reason why the folder names are prefixed with a period as this seems to go against a generally accepted standard for naming conventions?

FYI - this is in reference to the DevOps Pipelines wiki page here:
https://github.com/azure/azops/wiki/azure-pipelines

**Comment by daltondhcp** [comment]
Thanks for reaching out with your question about the .github, .vscode, and .devcontainer directories. It's great to see your engagement with the project!

To clarify, these folders are standard in many GitHub repositories and serve specific purposes:

- **.github:** This folder typically contains GitHub-specific files like workflow templates for GitHub Actions, issue templates, and contribution guidelines. It helps in automating and streamlining various GitHub processes. For more details, you can check out GitHub's documentation [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#about-github-actions).


- **.vscode:** This directory is used when the project is opened in Visual Studio Code (VSCode). It contains settings specific to the editor, such as code formatting rules, recommended extensions, and debug configurations. It ensures a consistent development environment for all contributors. More info can be found on the VSCode documentation page [here](https://code.visualstudio.com/docs/getstarted/settings).


- **.devcontainer:** This folder holds configuration files for the Visual Studio Code Remote - Containers extension. It allows developers to work in a Docker container environment, ensuring that everyone has the same tools and dependencies, regardless of their local setup. You can learn more about it [here](https://code.visualstudio.com/docs/remote/containers).

These folders are not directly related to the core functionality of the project but are crucial for maintaining consistency and efficiency in development practices, especially in collaborative settings. If they are not relevant to your use case, you can typically ignore them without impacting the main functionality of the project.

Hope this helps! Let us know if you have any more questions.

**Comment by greyghostbrewery** [comment]
This is actually related to the wiki page listed in the issue, and not the folder names you have listed, specifically the .pipelines & .scripts folders.

<img width="224" alt="image" src="https://github.com/Azure/AzOps/assets/12228748/97333f76-5daa-4863-b37e-978408de123b">
