### ISSUE TITLE
WhatIf report fails with Cannot bind argument to parameter 'FilePath' because it is null

### ISSUE THREAD

**Issue by bjompen** [Azure/AzOps#853]
**Describe the bug**

Verify and create feedback / WhatIf report fails with `Cannot bind argument to parameter 'FilePath' because it is null`
See image 1 for error, Error 2 for context.

In certain scenarios it appears that WhatIf fails as above. Setting message.info.maximum = 9 and enabling system.debug in Azure DevOps to get all messages let us track the error down to the following scenario:

We are running a serial deploy (Image 3) so in Invoke-AzOpsPush we are _either_ in line [497](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/functions/Invoke-AzOpsPush.ps1#L497), line [508](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/functions/Invoke-AzOpsPush.ps1#L508) or line [513](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/functions/Invoke-AzOpsPush.ps1#L513)

Inside New-AzOpsDeployment in out scenario we are running a bicep/json file the scope set is resource group and we end up inside [this if statement](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/internal/functions/New-AzOpsDeployment.ps1#L101)

Here we run `Set-AzOpsContext` which is a wrapper around `Set-AzContext`

The issue now is that Set-AzContext outputs the result of the context switch, and back in the calling script, Invoke-AzOpsPush, the output from Set-AzContext is caught in the `$DeploymentResult` variable.

In line [518](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/functions/Invoke-AzOpsPush.ps1#L518) we output `$DeploymentResult` to log as can be seen in image 2, and it now contains two objects:
- Output from Set-AzContext (unwanted)
- Output from New-AzOpsDeployment (wanted)

The [foreach loop](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/functions/Invoke-AzOpsPush.ps1#L520) following the output fails because the first object is a context object thatm logically enough, doesn't have a `$_.filePath` property.

**Steps to reproduce**

Run a verify pipeline with a bicep file?  I honestly don`t know if it hits every time, or only when you have to change context.

**Extra stuff**

I can of course share complete logs, but since they contain sensitive data we can take that in private if needed.

Proposed solution would be to simply change lines [103](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/internal/functions/New-AzOpsDeployment.ps1#L103) and [112](https://github.com/Azure/AzOps/blob/fba65e8fe6c4b4b064017c71dce5bca903b0483f/src/internal/functions/New-AzOpsDeployment.ps1#L112) in `New-AzOpsDeployment` to `$null = Set-AzOpsContext -ScopeObject $scopeObject` instead and simply ignore any output from it. Let me know if this is good and I'll fix it right away.

**Screenshots**

Image 1:
![image](https://github.com/Azure/AzOps/assets/17783007/1a41bc10-1001-4f09-9066-1dfbc3ffcb73)

Image 2:
![image](https://github.com/Azure/AzOps/assets/17783007/66bf3d72-0651-4db0-8d62-d153193912bf)

Image 3:
![image](https://github.com/Azure/AzOps/assets/17783007/ef99d36f-8b03-4a5d-96dc-eb4ded2496bc)

**Comment by bjompen** [comment]
Added suggested solution to referenced PR #854

**Comment by Jefajers** [comment]
Hi @bjompen, I can reproduce the scenario quite frequently 👍 .

Thanks for a great and through report and suggesting a fix 🥇 .
