### ISSUE TITLE
Issue evaluating jq version

### ISSUE THREAD

**Issue by danielnicanl** [Azure/AzOps#865]
**Describe the bug**
When running the azops 2.5.2 pull pipeline, the validation fails when the latest Jq package is installed .

**Steps to reproduce**

1. Create a Windows 2022 image and add all the package dependencies 
2. Run azops pull pipeline using the latest image

**Screenshots**
VERBOSE: Loading module from path 'C:\a\1\Modules\AzOps\2.5.2\AzOps.psm1'.
Assert-AzOpsJqDependency : Cannot convert value "1.7.1" to type "System.Double". Error: "The input string '1.7.1' was not in a correct format."
At C:\a\1\Modules\AzOps\2.5.2\AzOps.psm1:4313 char:9
+         Assert-AzOpsJqDependency -Cmdlet $PSCmdlet
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Assert-AzOpsJqDependency], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToDoubleOrSingle,Assert-AzOpsJqDependency
##[debug]Exit code: 1

**Comment by eosho** [comment]
I got this same error less then 20 mins ago. Ended up downgrading jq to 1.6.

**Comment by Jefajers** [comment]
Hi @danielnicanl thanks for reporting this, I have been able to reproduce the issue and we are working on a fix. In the meantime just as suggested by @eosho one workaround is to stick to 1.6.0.
