### ISSUE TITLE
PolicySetDefinition empty defaultValue is removed

### ISSUE THREAD

**Issue by jleechpe** [Azure/AzOps#874]
**Describe the bug**

PolicySetDefinitions require a `"defaultValue":` for parameters.  In cases where there is no default the json returned is `"defaultValue": ""` which is then omitted by the `jq` template.

Trying to update a policysetdefinition that was returned with empty values fails because it is missing the default values for the parameters.  Adding them into the template is a work-around since the next `Invoke-AzOpsPull` will remove them once again.

**Comment by Jefajers** [comment]
Hi @jleechpe, thanks for reporting this.

I am able to reproduce the scenario and will pursue remediation for policy definitions and policy set definitions.
